docs/content/en/advanced.md, docs/content/en/configuration.md
This PR fixes some small typos in the docs.
=> docs: typo

docs/content/en/advanced.md
=> fixed typos

lib/middleware.js
This should fix #54 by decodeURI request url before searching query
=> fix: decodeURI before searching query

docs/content/en/fetching.md, example/content/articles/2020/04/april-newsletter.md, example/content/articles/2020/05/may-newsletter.md, example/pages/articles/_year/_month/_slug.vue, example/pages/articles/_year/_month/index.vue, example/pages/articles/index.vue, lib/database.js, lib/index.js, lib/middleware.js, lib/templates/plugin.client.js, lib/templates/plugin.static.lazy.js, lib/templates/query-builder.js, test/fixture/content/articles/2020/04/april-newsletter.md, test/fixture/content/articles/2020/05/may-newsletter.md, test/module.test.js, test/server.test.js, types/index.d.ts
=> Deep fetch

docs/content/fr/advanced.md, docs/content/fr/configuration.md, docs/content/fr/displaying.md, docs/content/fr/fetching.md, docs/content/fr/index.md, docs/content/fr/installation.md, docs/content/fr/theme.md, docs/content/fr/writing.md, docs/nuxt.config.js
Tried to translate as better as I could, don't hesitate to ask for changes
=> docs: Translated docs into French

docs/content/ru/advanced.md
=> docs: fix mismatched function names in feed example code

docs/content/en/index.md, docs/content/en/writing.md, docs/content/fr/index.md, docs/content/fr/writing.md, docs/content/ru/index.md
=> docs: Fix package name

docs/content/ja/advanced.md, docs/content/ja/changelog.md, docs/content/ja/configuration.md, docs/content/ja/displaying.md, docs/content/ja/fetching.md, docs/content/ja/index.md, docs/content/ja/installation.md, docs/content/ja/theme.md, docs/content/ja/writing.md, docs/i18n/ja_JP.js, docs/nuxt.config.js
The document has been translated into Japanese.
Support for locates has been added.
Thanks for a great module.
=> docs: Translated docs into Japanese

docs/content/ru/displaying.md
=> docs: Updated displaying.md

docs/content/ru/changelog.md
=> docs: Translated changelog.md into Russian

docs/content/en/fetching.md, docs/content/fr/fetching.md, docs/content/ja/fetching.md, docs/content/ru/fetching.md, lib/middleware.js, lib/query-builder.js, lib/templates/plugin.static.js, lib/templates/query-builder.js, test/module.test.js, test/plugin.test.js, test/server.test.js
=> feat: without fields

docs/content/en/writing.md
add an example for table of contents usage
=> docs: (en) add example for toc

docs/content/en/fetching.md
Add an example for using previous and next
=> docs: (en) add prev next example

docs/package.json, docs/yarn.lock
=> docs: update nuxt-static

docs/content/en/fetching.md
=> docs: fix Content API link

lib/index.js
=> chore: add content:ready hook

lib/database.js, lib/index.js, lib/middleware.js, package.json
=> chore: replace fs with graceful-fs

docs/content/en/writing.md
=> docs: grammar fix: it's -> its

README.md
This is just to sync the file types as listed in the official site https://content.nuxtjs.org. 
With that said, the description of this repo is also missing XML, so I'm not sure whether it's a character limit or not. I hope not haha
=> add missing XML file type in README.md

docs/content/en/configuration.md, docs/content/en/writing.md, lib/index.js, lib/templates/plugin.client.js, lib/templates/plugin.server.js, lib/utils.js
=> feat: add option to disable live edit

docs/content/en/themes-docs.md
=> fix: docs link point to localhost

docs/content/en/themes/docs.md, packages/theme-docs/src/index.js
=> fix: use defu extend

packages/theme-docs/src/i18n/es-ES.js
Add Locale i18n es-ES Support
Add new file to support spanish language
=> feat(theme-docs): add locale spanish support

packages/theme-docs/src/i18n/de-DE.js
This PR adds a German locale (de-DE) for @nuxt/content-theme-docs.
```js
i18n: {
locales: () => [
{
code: "de",
iso: "de-DE",
file: "de-DE.js",
name: "Deutsch",
},
];
}
```
=> feat(theme-docs): add german locale

docs/content/en/themes/docs.md, packages/theme-docs/package.json, packages/theme-docs/src/assets/css/tailwind.css, packages/theme-docs/src/index.js, yarn.lock
=> feat: use tailwind css module v3

docs/content/en/themes/docs.md, packages/theme-docs/src/components/global/app/AppHeader.vue, packages/theme-docs/src/components/global/app/AppNav.vue, packages/theme-docs/src/components/global/app/AppPrevNext.vue, packages/theme-docs/src/components/global/app/AppToc.vue, packages/theme-docs/src/layouts/single.vue, packages/theme-docs/src/pages/_.vue
=> feat(theme-docs): add single page layout setting

packages/theme-docs/src/plugins/init.js, packages/theme-docs/src/store/index.js
=> fix: hide releases if empty

packages/content/lib/index.js, packages/content/lib/utils.js
Use `defu.arrayFn` to merge options
=> fix(content): use defu.arrayFn instead of custom merger

packages/theme-docs/src/components/global/app/AppNav.vue
Twitter link don't work on mobile menu.
Actual: https://content.nuxtjs.org/%60https://twitter.com/$%7Bsettings.twitter%7D%60
Expected: https://twitter.com/nuxt_js
=> fix(theme-docs): fix Twitter link

packages/theme-docs/src/index.js, packages/theme-docs/src/pages/_.vue
Add an index route for prefixed locales: `/fr` 
Resolves #412
=> fix(theme-docs): extend `/` route

packages/theme-docs/src/components/global/base/Alert.vue
When there is code inside alert, the container overflows or is too small.
Before:
After:
=> fix(theme-docs): fix code display inside alert

packages/theme-docs/src/components/global/app/AppNav.vue
`.dark-mode .dark\:bg-gray-900` overrides `.lg\:bg-transparent` in dark mode.
No problem in light mode.
=> fix(theme-docs): fix aside background in dark mode

packages/theme-docs/src/i18n/ne-NP.js
I get the missing translation file when used my local language.
Just adding a new translation file for the docs-theme
=> Add Nepali translation file ne-NP.js

packages/theme-docs/src/assets/css/main.css, packages/theme-docs/src/assets/css/main.dev.css, packages/theme-docs/src/index.js
Before (light mode):
Before (dark mode):
After (light mode):
After (dark mode):
=> fix(theme-docs): improve live edit styles

packages/content/lib/index.js, packages/content/templates/plugin.static.js
Write `db.json` with hash on fs: `db-${hash}.json`.
=> fix(content): write db.json with hash

packages/theme-docs/src/plugins/markdown.js
=> fix(theme-docs): fix empty title on links

packages/content/package.json, yarn.lock
Add detab in package.json (https://github.com/syntax-tree/mdast-util-to-hast/commit/914a6b77b9d363c588dcc6ef61f96053ec1b3b1e removed it from dependencies!)
fixes #448
=> fix: missing package detab

docs/content/en/advanced.md, packages/content/lib/database.js, packages/content/lib/index.js
see #432 
alternative / addition? to #450 
Example:
```ts
hooks: {
'content:file:beforeParse': (file) => {
if (file.extension !== '.md') return
file.data = preParser(file.data)
}
}
```
=> feat: add content:file:beforeParse hook

docs/content/en/fetching.md
=> docs: remove fetch from  since nuxt 2.12

packages/theme-docs/src/i18n/zh-CN.js
This PR adds a simplified chinese locale (zh-CN) for @nuxt/content-theme-docs.
=> feat(theme-docs): add locale simplified chinese support

docs/content/en/index.md
Adds link to tutorial on the nuxt blog
Adds link to tutorial on the nuxt blog
=> docs: add tutorial to docs

packages/theme-docs/src/pages/releases.vue
=> fix(theme-docs): handle single layout on releases

docs/content/en/themes/docs.md, packages/theme-docs/src/components/global/base/List.vue
=> feat(theme-docs): add variant and icon support in `list` component

docs/content/en/themes/docs.md
Added firebase.nuxtjs.org to showcases
Added firebase.nuxtjs.org to showcases.
=> Added firebase.nuxtjs.org to showcases

docs/content/fr/writing.md
Replacing `<nuxt-conent>` by `<nuxt-content>`.
=> docs: typo on french documentation page

docs/content/en/themes/docs.md
Added Nuxt PWA to docs theme showcases.
=> docs: add Nuxt PWA to docs theme showcases

docs/content/en/themes/docs.md
Added Nuxt Image to docs theme showcases.
=> docs: add Nuxt Image to docs theme showcases

docs/content/en/fetching.md
Added catch() after fetch() to prevent error.
=> docs: describe `catch` in fetching methods

packages/content/lib/index.js, packages/theme-docs/src/index.js
=> fix: avoid registering `components/global` when not exists

packages/theme-docs/src/index.js, packages/theme-docs/src/tailwind.config.js
=> fix(theme-docs): handle purgecss in rootDir components

packages/theme-docs/src/i18n/pl-PL.js
=> feat(theme-docs): add locale polish support

packages/theme-docs/src/i18n/tr-TR.js
=> feat(theme-docs): add locale turkish support

packages/theme-docs/src/tailwind.config.js
TailwindCSS added 2 new flags: 
- [defaultLineHeights](https://tailwindcss.com/docs/upcoming-changes#default-line-heights-for-font-size-utilities)
- [standardFontWeights](https://tailwindcss.com/docs/upcoming-changes#rename-font-thin-and-font-hairline)
This PR adds them by default for the theme docs.
=> feat(theme-docs): Add new tailwindcss future flags

docs/content/fr/advanced.md, docs/content/fr/configuration.md, docs/content/fr/displaying.md, docs/content/fr/fetching.md, docs/content/fr/writing.md
=> docs: fix fr links

docs/content/en/advanced.md, packages/content/lib/index.js
Add `content:options`  hook, this is useful for modules to read or update Content configuration, this would be useful for the admin panel :)
=> chore: add content:options hook

packages/content/parsers/markdown/handlers/code.js
=> fix(content): support space after codeblock for filename

packages/theme-docs/src/index.js, packages/theme-docs/src/tailwind.config.js
=> fix(docs-theme): support overwriting hooks

docs/content/en/fetching.md, docs/content/en/snippets.md, packages/content/lib/middleware.js, packages/content/lib/query-builder.js, packages/content/templates/query-builder.js, packages/content/test/fixture/content/positioned/category-1/answer.md, packages/content/test/fixture/content/positioned/category-1/challenge.md, packages/content/test/fixture/content/positioned/category-1/introduction.md, packages/content/test/fixture/content/positioned/category-2/answer.md, packages/content/test/fixture/content/positioned/category-2/challenge.md, packages/content/test/fixture/content/positioned/category-2/introduction.md, packages/content/test/module.test.js, packages/content/test/plugin.test.js, packages/content/test/server.test.js, packages/content/types/query-builder.d.ts, packages/theme-docs/src/pages/_.vue
=> feat(content/theme-docs): support surround by path

docs/content/en/fetching.md, docs/content/ja/fetching.md
Just a spelling correction
- [] I have added tests to cover my changes (if not applicable, please state why)
=> docs: correct spelling errors

packages/content/lib/query-builder.js
I found when testing my search, that I was receiving strange results, with relevant ones mixed in with not so relevant ones. I spent a while digging, and found that the results are not being sorted at all.
When you perform a search, it is normally expected that the results will be sorted by the **most relevant** results first. 
The existing `search()` method does not do this, and it is not possible to use `sortBy()` to sort by the underlying full text search score from LokiDB.
LokiDB offers a method to `sortByScoring()` which must be used to ensure the most relevant results are returned.
https://github.com/LokiJS-Forge/LokiDB/blob/master/packages/loki/src/result_set.ts#L377
https://github.com/LokiJS-Forge/LokiDB/blob/master/packages/full-text-search/spec/generic/full_text_search.spec.ts#L2 …
=> feat: sort by score (most relevant first) when searching

docs/content/en/advanced.md
There is no explanation about `database` argument of `content:file:beforeInsert` hook, which was introduced by #442.
This PR is to add description of it.
I checked UI in my local by running `yarn run dev` in `docs` directory.
=> docs: add missing description

packages/theme-docs/src/i18n/ko-KR.js
Add i18n locale file for Korean language.
Should I test this kind of change?
=> feat(theme-docs): add korean locale

packages/theme-docs/src/i18n/nl-BE.js
Adds the `nl-BE.js` localization file with translated strings for the docs theme. Resolves #738.
=> feat(theme-docs): Added nl-BE.js localization file to docs theme

packages/content/parsers/markdown/handlers/code.js
This PR add support for syntax highlighting in `diff` language using [`diff-highlight`](https://github.com/PrismJS/prism/blob/master/plugins/diff-highlight/prism-diff-highlight.js) plugin. Initially reported in https://github.com/nuxtlabs/docus/pull/32
=> feat: use diff-highlight plugin

docs/content/en/fetching.md, docs/content/en/snippets.md
None of above: update on docs
This PR is based on #695 and is to add description about behavior of `sortBy` method, that is, the sorting is case sensitive.
I also added a snippet by which to work around the behavior.
For more detail, please refer to #695.
In my local, I ran `yarn run dev` in `docs` directory and checked UI.
=> docs: add description about sort-by method

docs/content/en/fetching.md
None of above: update on docs
I replaced a version placeholder with actual version, v1.12.0, in which #600 is released ([CHANGELOG](https://github.com/nuxt/content/blob/dev/packages/content/CHANGELOG.md#features)).
In my local, I ran yarn run dev in docs directory and checked UI.
=> docs: fix version placeholder

docs/content/en/integrations.md, docs/content/fr/integrations.md
Fix typo in the content feed integration documentation example . There was a missing "," in the example 2.  
It is just a typo fix in the documentation.
=> docs(content): fix typo in feed integration example

packages/create-nuxt-content-docs/src/saofile.js
Resolves: #773
Test notes:
- Link my local `create-nuxt-content-docs` package
- Run `npx create-nuxt-content-docs <project_name>`
- Select `Npm` when asked Package manager
As a result, SAO used npm as client.
=> fix(create-nuxt-content-docs): respect npm client answer

packages/content/parsers/markdown/index.js
Use reduce to support Node v10
resolves #769
=> fix(content): avoid usage of flatmap in markdown to support node v10

packages/content/templates/nuxt-content.js, packages/content/templates/plugin.client.js, packages/content/templates/query-builder.js
=> fix(content): avoid using commonjs for runtime (vite support)

docs/content/en/displaying.md, docs/content/en/writing.md
There is no documentation on how to render the excerpt from the markdown file. Currently requires a specific object shape for it to work, so I thought it'd be best to document it while the team figures out a possible alternative.
Just doc changes, no tests needed.
Related to https://github.com/nuxt/content/issues/686
=> docs: improve excerpt examples

docs/content/fr/themes/docs.md
Remove the English sentence above French one in French content.
=> docs(fr): remove untranslated sentence

docs/content/en/advanced.md, docs/content/en/configuration.md, docs/content/en/displaying.md, docs/content/en/index.md, docs/content/en/integrations.md, docs/content/en/snippets.md, docs/content/en/themes/docs.md, docs/content/en/writing.md, packages/content/lib/index.js, packages/content/parsers/csv/index.js, packages/content/parsers/markdown/compilers/json.js, packages/content/parsers/markdown/handlers/utils.js, packages/content/parsers/markdown/index.js, packages/content/parsers/xml/index.js, packages/content/parsers/yaml/index.js, packages/content/types/parsers/csv/index.d.ts, packages/content/types/parsers/markdown/index.d.ts, packages/content/types/parsers/xml/index.d.ts, packages/content/types/parsers/yaml/index.d.ts
…ents
This PR fixes grammatical errors and typos in the English documentation as well as a few code comments.
=> docs: fixes grammar mistakes and typos in documentation and code comments

packages/theme-docs/src/i18n/pt-PT.js
Added the i18n Portuguese native translation (pt-PT).
I think it does not require any further change. Simple addition.
=> feat(theme-docs): Add Portuguese Translation for Docs Theme (pt-PT)

packages/theme-docs/src/i18n/de-DE.js
This commit introduces a missing translation key of the german locale
No tests added as this is just a missing translation key.
=> fix(theme-docs): updated german locale

docs/content/ru/themes/docs.md
adds missing configuration keys to the Russian documentation: `githubApi`, `defaultDir` and `algolia` options described
=> docs(content): Russian documentation update

packages/theme-docs/src/i18n/zh-CN.js
=> feat(theme-docs): update locale simplified Chinese translation

packages/theme-docs/src/i18n/pt-BR.js
=> feat(theme-docs): add Brazilian Portuguese translation file

docs/content/ja/displaying.md
=> fix(docs): fix a typo

packages/content/types/query-builder.d.ts
Resolves: #985.
There is no unit test for type exporting.
=> feat(content): export FetchReturn type

packages/theme-docs/src/i18n/tr-TR.js
[Reopen #988](https://github.com/nuxt/content/pull/988)
=> fix(theme-docs): Add updatedAt keypath to tr-TR.js

docs/content/en/fetching.md
=> docs(content): fix spelling error

docs/content/en/installation.md
Minor documentation change
There are some capitalization issues I've changed; from "nuxt" to "Nuxt" and "typescript" to "TypeScript" from the Installation page I found while reading through the docs.
=> fix(docs): minor capitalization fix

docs/content/1.getting-started/1.installation.md, docs/content/1.getting-started/2.your-first-page.md, docs/content/2.guide/1.writing-content/1.content-directory.md, docs/content/2.guide/1.writing-content/2.front-matter.md, docs/content/2.guide/2.displaying-content/1.fetching.md, docs/content/2.guide/2.displaying-content/2.rendering.md, docs/content/2.guide/3.syntax/1.mdc.md
This PR adds small improvements to sentences to make them more direct and clear.
=> docs(wording): improve docs sentences

README.md
=> docs(readme): update shiki url

docs/content/1.getting-started/2.your-first-page.md
This PR fixes a missing closing tag on `code-group` component
=> docs(tutorial): fix closing tag on codegroup

docs/content/en/integrations.md
I spent some time looking to use Nuxt content with @nuxt/i18n and found the solution in #44. I think having that response in the documentation would have saved me time.
=> docs(docs): add l10n and i18n snippet

packages/theme-docs/src/i18n/es-ES.js
Add missing keyPath to updatedAt in es-ES i18n translations
=> fix(theme-docs): Add updatedAt keypath to es-ES.js

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md
This PRs adds bug-report and feature-request issue templates.
=> docs(repo): migrate issue templates from v1

examples/navigation/fetch-content-navigation/app.vue
Use `AppNavigation` component to display navigation tree in example
=> docs(examples): use app-navigation component

docs/content/2.guide/1.writing/2.markdown.md
Update front-matter properties table
=> docs(front-matter): update front-matter properties

src/module.ts, src/runtime/server/index.ts, src/runtime/server/storage.ts, src/runtime/server/transformers/index.ts, test/fixtures/basic/server/api/parse.ts
=> feat: expose server utils in `#content/server`

src/runtime/server/navigation.ts, test/__snapshots__/basic.test.ts.snap, test/fixtures/basic/content/cats/bombay.md
=> fix(navigation): sort contents by path

.github/ISSUE_TEMPLATE/bug-report.yml, docs/content/1.getting-started/1.installation.md
This PR updates the starter and repro URL to use https://github.com/nuxt/starter/tree/content-v2
=> docs(starter): update repo url

src/module.ts, src/runtime/server/storage.ts
=> feat(cache): respect module version

playground/pages/playground.vue, playground/pages/query.vue, src/runtime/components/Prose/ProseCode.vue, src/runtime/components/Prose/ProseCodeInline.vue
We should not ship any style by default.
=> fix(prose): remove default style

docs/content/4.api/1.components/3.content-navigation.md
=> docs: typo data to navigation

src/runtime/server/navigation.ts, test/__snapshots__/basic.test.ts.snap, test/fixtures/basic/content/cats/_dir.yml, test/fixtures/basic/content/cats/index.md
=> fix(navigation): fix  `_dir` detection for index pages

src/module.ts
=> fix(module): invalidate cache on options change

docs/content/3.guide/2.displaying/2.querying.md
This PR fixes a bad value that was inserted for testing purposes
=> docs(querying): fix example json title

src/module.ts, src/runtime/server/storage.ts
based on @pi0  comment https://github.com/nuxt/content/pull/1129#discussion_r880585571
=> fix: separate cache version from integrity

docs/content/3.guide/2.displaying/1.rendering.md
=> docs: correct spelling of ContentDoc

docs/content/2.get-started.md
=> docs: content comment is now link to option docs

docs/content/3.guide/2.displaying/1.rendering.md
spelling error `Note` and not `not`
=> chore: typo Rendering Doc

docs/content/3.guide/1.writing/3.mdc.md
fix: typo that->than, highlight span to improve comprehension
=> fix: typo that->than, highlight span to improve comprehension

src/runtime/types.d.ts
fix #1180
Renamed the `_title` to `title`
=> fix(types): `_title` rename to `title`

docs/content/3.guide/1.writing/3.mdc.md
=> docs: fix missing slash

docs/content-v1/en/1.getting-started/2.installation.md
=> docs: specify version in v1 installation guide

src/runtime/server/transformers/path-meta.ts, test/features/transformer-path-meta.ts
=> fix: handler files with `index` as substring

package.json, src/runtime/server/api/highlight.ts
=> fix(highlight): remove `@nuxt/kit` from runtime bundle

src/runtime/plugins/documentDriven.ts
Disabling page or navigation in document-driven will cause reducing promises length and therefore leads to invalid behavior.
=> fix(document-driven): add empty promise for disabled features

src/runtime/composables/head.ts
=> fix: clone `head.meta` before manipulating

docs/content/4.api/4.advanced.md
Added the article 'a' to a sentence (grammar).
=> docs: add article 'a' to sentence

src/runtime/pages/document-driven.vue
=> fix: import `useRoute`

package.json
=> chore: remove `unctx` from dependencies

src/runtime/server/content-index.ts
Resolve priority issues in duplicate pathes
=> fix(content-index): higher priority for `content` directory 

src/runtime/markdown-parser/handler/list.ts
Add missing class for GFM task list.
=> fix(markdown): add missing task list class

docs/content/4.api/1.components/6.prose.md, docs/content/4.api/3.configuration.md
=> docs: describe `highlight.preload` 

src/runtime/transformers/json.ts, test/features/parser-json.ts, test/fixtures/basic/content/_partial/simple-json.json
=> fix(json): handle parsed content

docs/content/3.guide/1.writing/7.document-driven.md
- added option to use `pnpm` as CLI
- moved `npx` & `pnpm` options into a code group
=> docs(document-driven): add pnpm as project start option

src/runtime/transformers/markdown.ts
This is needed when using `transformContent` on client-side in a web worker for instance.
=> fix(runtime): allow to give instance of the remark plugin

src/module.ts, test/basic.test.ts, test/features/components.ts, test/fixtures/basic/content/LoremIpsum.vue, test/fixtures/basic/content/components/from-content.md, test/fixtures/basic/nuxt.config.ts
=> fix(module): do not add vue files to ignore list

package.json, playground/shared/components/NavItem.vue, src/module.ts, src/runtime/index.ts, src/runtime/utils/query.ts, yarn.lock
=> chore: upgrade to nuxt rc9

src/runtime/components/Markdown.vue
=> fix(`<MarkDown>`): prevent multiple deprecation log

src/module.ts
=> perf(build): build caches before pre-rendering contents

src/module.ts
=> fix(module): make `documentDriven` configs optional

docs/content/3.guide/4.deploy/2.static-hosting.md
=> docs: fix typo `client only` -> `client-only`

docs/app.config.ts, docs/nuxt.config.ts, docs/package.json, docs/tokens.config.ts, docs/yarn.lock
Resolves #1540 
Need to check the token since no result are returned
=> docs: add search

src/runtime/markdown-parser/handler/link.ts
Before:
`[Test](./1.test.md)` -> `/1.test.md`
After:
`[Test](./1.test.md)` -> `/test`
=> fix: use relative `.md` link

src/utils.ts
=> fix(module): multi-source array

docs/content/4.api/2.composables/1.query-content.md
=> docs: update `findSurround` usage

src/module.ts
=> fix(module): set default hostname for dev socket

src/runtime/plugins/documentDriven.ts
Seems that `__asyncLoader` does not exist anymore.
=> fix(dd): layout prefetching

package.json, test/features/parser-markdown.ts, yarn.lock
=> chore: upgrade deps

src/runtime/components/ContentRenderer.vue, test/basic.test.ts, test/fixtures/basic/pages/features/empty-slot.vue
=> fix(ContentRenderer): empty content detection

docs/nuxt.config.ts, docs/package.json, docs/yarn.lock
=> docs: update deps

.gitignore, docs/package.json, docs/yarn.lock
Upgrade `studio-module` to take profit of last feature
=> docs: update studio module

docs/content/5.examples/5.navigation/1.fetch-content-navigation.md
=> docs: fix typo

src/runtime/composables/utils.ts
=> fix(clientDB): disable clientDB if token is set and has falsy value

src/runtime/plugins/documentDriven.ts
=> fix(document-driven): prevent `404` error on redirected pages

docs/content/3.guide/3.recipes/1.sitemap.md
=> docs: update outdated link in `sitemap.md`

docs/content/2.get-started.md
Fix a broken link in the documentation.
=> docs: Fix broken quickstart link

docs/content/3.guide/4.deploy/1.node-server.md
Fix broken link to nuxt node server deploy page
=> docs: fix broken nuxt link

examples/essentials/document-driven/app.vue
=> fix(examples): fix layout duplication

docs/content/4.api/1.components/2.content-list.md
fix ContentDoc multi-Slot Example
- [] I have updated the documentation accordingly.
=> docs: fix ContentDoc multi-slot example

docs/content/4.api/4.advanced.md
Note about the position of `@nuxt/content` and the transformers loader.
=> docs: add note about transformer

src/runtime/composables/head.ts, test/fixtures/basic/.nuxtrc, test/fixtures/basic/pages/features/query-content.vue, test/fixtures/basic/pages/features/slotted-content-renderer.vue, test/fixtures/basic/pages/locale-[locale].vue, test/fixtures/basic/pages/nav-with-query.vue, test/fixtures/basic/pages/parse.vue, test/fixtures/document-driven/pages/custom-search.vue, test/fixtures/document-driven/pages/disabled.vue, test/fixtures/document-driven/pages/home.vue, test/fixtures/document-driven/pages/no-surround.vue
=> test: disable autoImport on tests

src/runtime/components/Prose/ProseImg.vue
=> fix(markdown): images src with `baseURL`

docs/app.config.ts
This must be edited according to docs https://docus.dev/introduction/configuration
=> docs: update edit path

docs/content-v1/en/1.getting-started/7.advanced.md
Removes extraneous typo from code sample
=> docs: remove extraneous comma

src/module.ts
#1856
Adds the correct type to the `anchorLinks` option
=> fix: add type to anchorLinks option

docs/content/4.api/3.configuration.md
=> docs: update documentDriven config

docs/content/3.guide/1.writing/3.mdc.md
=> docs: add example for using v bind with inline mdc props

src/module.ts
=> fix(module): close dev server on nitro close

src/runtime/query/query.ts
=> fix(query): prevent adding duplicate conditions to query

package.json, pnpm-lock.yaml
Minor change, but should enable better hoisting behaviour in future when installing nuxt/content.
=> chore: use caret dependency for kit

docs/content/4.api/3.configuration.md
Updating documentation to show how to add custom grammars for code syntax highlighting using Shiki. Had to dig around a while to figure this out. I hope this doc update this can help others.
=> docs: guide for adding custom grammars for syntax highlighting

package.json, pnpm-lock.yaml
fix #2063
`pnpm install unist-util-stringify-position`
Resolves #2063
=> chore(deps): Install unist-util-stringify-position

docs/content/5.examples/6.templates/1.content-wind.md
Live demo url of **Content Wind** nuxt template has been fixed/updated.
=> docs: update live demo url of `Content Wind`

README.md
Update the development section of readme
=> doc: update readme development : yarn to pnpm

src/module.ts
=> fix(module): add `yml` / `json` extensions to tailwind content files

src/module.ts
This is a minor issue, but `addComponentsDir` is a synchronous function.
=> chore: remove unneeded await

src/runtime/markdown-parser/index.ts
=> fix: remark plugins deprecated warning

docs/content/4.api/2.composables/1.query-content.md
=> docs: add count method

package.json, pnpm-lock.yaml, src/runtime/transformers/csv/from-csv.ts
micromark v4 now properly exports the processing functions
=> chore: update to micromark v4

src/runtime/query/match/pipeline.ts, src/runtime/query/query.ts
=> fix(findSurround): use filtered contents to find surround

src/runtime/query/match/pipeline.ts
=> fix(surround): respect `only` and `without` filters

package.json, pnpm-lock.yaml
=> fix: add missing dependencies

docs/content/3.guide/1.writing/3.mdc.md
Connected to:
https://github.com/nuxt/content/issues/1709
=> Add warning about prettier and workaround

src/runtime/components/Prose/ProsePre.vue
This change fixed a compatibility issue with themes
=> fix(prose-pre): only wrap `slot` in `pre`

docs/content/2.usage/3.files.md
Updating file usage examples to use findOne().
This updates the documentation for the example queries on the file usage page to use the correct function findOne().
=> docs: update file usage example queries

docs/content/index.yml
=> docs: add links for shiki on home

package.json, src/runtime/types/index.d.ts
This PR add types to the layout key.
=> feat: add type to layout

docs/content/1.get-started/2.configuration.md
Update highlight.preload config for adding new grammars to match current Shiki version.
https://github.com/nuxt/content/issues/2384
=> docs: update highlight.preload config

.nuxtrc, src/runtime/composables/search.ts
fix #2404
I fix some imports issues. I also add `.nuxtrc` file to avoid auto-import and to detect missing imports.
=> fix: add missing imports for search

package.json
to add https://content.nuxt.com here : https://www.npmjs.com/package/@nuxt/content
=> feat: add homepage on package.json

docs/content/2.usage/3.search.md
Just resolves a small typo in the docs.
=> docs(content): small typo

docs/content/index.yml
fixed typo in "deploy everywhere" card
Updated `index.yml` to fix a couple typos and improve wording.
=> docs: update index.yml

docs/content/4.components/4.content-query.md
Fix component name typo
Fixing component name typo
=> docs: fix component name

src/module.ts
Incoming change in `@nuxtjs/tailwindcss`; refer https://github.com/nuxt-modules/tailwindcss/pull/792
=> chore(tw-support): get cssPath from array

src/runtime/composables/search.ts
=> fix: missing import

src/runtime/server/storage.ts
resolves https://github.com/nuxt/content/issues/2602
=> fix: ignore unsupported files from contents list

docs/content/6.recipes/2.transformers.md
The section on transformers is unclear and outdated
=> docs: fix and update transformers

docs/README.md
Social cards in `docs/README.md` were not displayed.
After investigating the cause, it appears that the image file name has been changed.
=> docs: fix social card in README

src/module.ts, src/runtime/server/search.ts, src/types/module.ts
=> fix(search): improve sections with root node

docs/content/1.get-started/2.configuration.md
=> Fix typo 2.configuration.md

src/runtime/server/search.ts
=> fix(search): handle missing description when file is not a markdown

src/module.ts
=> fix(module): disable MDC plugin if user disabled it

src/module.ts
Add `@nuxtjs/mdc` dependencies into vite optimize list in order to use MDC module's utils without adding  it to project dependencies.
=> fix(module): allow using `@nuxtjs/mdc` utils via content module

docs/content/1.get-started/2.configuration.md
None
Fix missing import statement.
=> docs: missing imports and typo in code blocks

docs/pages/index.vue
Closes #2722 
Updated the `.gradient` class on the home page by adding `left: 0` to remove the scrollbar coming at the bottom
=> fix: corrected .gradient class

docs/content/1.get-started/1.installation.md
N/A
Typo correction in docs
PR I submitted yesterday snuck in with 'compatible' misspelled 'combatible'
=> fix(docs): fix typo in SSR warning on Installation page

src/runtime/server/api/cache.ts, src/runtime/server/api/navigation.ts, src/runtime/server/api/query.ts, src/runtime/server/api/search.ts, src/runtime/server/plugins/refresh-cache.ts
resolves https://github.com/nuxt/content/issues/2763
https://github.com/nuxt-modules/mdc/pull/253
=> fix(build): keep parser deps out of entrypoint

docs/content/docs/2.collections/1.collections.md
Update the 1.collections.md file by correcting the function name from "z.Date" to the proper lowercase version "z.date".
=> docs: Update 1.collections.md file fixing z.Date typo

docs/content/index.yml
=> docs: use yaml multiline format

docs/content/docs/3.files/1.markdown.md
Duplicate `Code Highlighting` section in `3.files/1.markdown.md`
=> docs: duplicate section in 3.files/1.markdown.md

src/module.ts
Related to this https://github.com/nuxt/content/commit/bd9e15b530484362158dcc5e4ceda3604b80582a  /cc @farnabaz
Refer to https://github.com/nuxt-modules/mdc/tree/main/src/runtime/components/prose add the remaining prose tags.
=> chore(module): add the remaining prose tags

docs/content/docs/7.studio/5.config.md
The docs were mentioning a wrong import to the studio
=> fix(docs): update import paths in configuration documentation

package.json, pnpm-lock.yaml, src/utils/content/index.ts
close: https://github.com/nuxt/content/issues/2940
https://github.com/shikijs/shiki/pull/879  since the new structure shikijs has been switched, this place gives an error on new installations.
=> feat: update import path for shiki languages

docs/content/index.md
Fix horizontal scrollbar on https://content3.nuxt.dev.
**Before:**
**After:**
=> style(website): fix horizontal scrollbar

src/runtime/app.ts, src/utils/collection.ts, test/unit/generateCollectionInsert.test.ts
SSR Event is undefined while executing query and it causes failed query in CF. We need to get the event on initializing queryBuilde.
=> fix: undefined ssr event & and invalid column update

src/types/query.ts
#1522 
- [x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Solves #1522
=> Fix: #1522 QueryBuilderParams type error

docs/app/components/post/PostPage.vue
=> docs(PostPage): surround order

docs/app/components/post/PostPage.vue
resolves #2984 
Fix Bluesky link in page TOC
=> docs: fix bsky link

src/utils/config.ts
This PR corrects the broken install link.
=> fix: fix broken install link

docs/content/changelog/frontmatter-form.md
=> docs(changelog): update frontmatter-form

docs/components/Banner.vue
=> docs(v2): update Banner

src/utils/dev.ts
resolves #2991
Unify path format on windows file watcher.
=> fix(module): collection detection on windown file-watcher

src/utils/content/index.ts
=> fix(parser): de-prioritise code highlighter plugin

docs/content/studio/pricing.yml
Update pricing.yml
Fix typo in feature table
=> docs: fix typo in feature table

docs/content/docs/1.getting-started/4.migration.md
n/a
This is a single-character typo fix.
=> fix: migration doc typo

package.json, pnpm-lock.yaml, src/module.ts, src/presets/cloudflare-pages.ts, src/presets/index.ts, src/presets/node.ts, src/presets/nuxthub.ts, src/presets/vercel.ts, src/runtime/api/query.post.ts, src/runtime/internal/database.server.ts, src/types/module.ts, src/utils/database.ts, src/utils/dev.ts, src/utils/preset.ts, test/basic.test.ts, test/bun.test.ts, test/empty.test.ts
Integrate with NuxtHub database in local development and leverage NuxtHub database queries to pre-fill database in production and achieve faster cold start
=> feat: integrate with NuxtHub database and database queries

docs/content/docs/1.getting-started/3.configuration.md, src/types/module.ts, src/utils/content/index.ts, src/utils/index.ts
=> feat(module): extend content transformers

README.md
=> docs(readme): current path links

docs/content/docs/1.getting-started/4.migration.md
=> docs: missing quote in migration

docs/content/docs/2.collections/3.sources.md
=> docs: override source prefix

src/runtime/internal/security.ts, test/unit/assertSafeQuery.test.ts
=> fix(query): allow uppercase in column names

src/presets/vercel.ts
=> fix(vercel): use `/tmp` directory for sqlite db

src/runtime/internal/database.server.ts
=> fix(database): prevent creating multiple database connections

src/utils/collection.ts, test/unit/generateCollectionInsert.test.ts
closes #3129
When running the depoyment of nuxt-content database on D1 on kestra.io we noticed some weird values in the database: 
- Concatenations that should not have been there. 
- Invalid JSON
- values partly duplicated
Before this PR, the system allowed for queries up to 200Kb to be split in 2. 
A query of 300Kb would have also be split in 2 (150 + 150) and fail.
In this PR, the system will run as many updates as needed.
=> feat(collection): repair SQL query slicing for content larger than 200Kb

docs/content/docs/3.files/1.markdown.md
None
Corrected heading level and wording in the documentation.
=> docs: correct heading level and wording

docs/content/docs/1.getting-started/3.configuration.md
=> docs(configuration): add mdc configuration note

src/runtime/internal/database.server.ts
=> fix: use a 90 seconds timeout to prevent Cloudflare from timing out

docs/content/docs/2.collections/1.define.md
=> docs: add define collection warning

docs/content/docs/7.advanced/5.hooks.md, src/types/content.ts, src/types/hooks.ts, src/types/index.ts, src/types/module.ts, src/utils/content/index.ts
resolves #3164
Define module hooks in `NuxtHooks` interface
=> fix(type): register module hooks types

docs/content/docs/8.studio/3.content.md
Studio section about form generation with zod schema.
=> docs(studio): form generation with zod

src/features/llms/runtime/server/content-llms.plugin.ts
=> fix(llms): add missing import for `defineNitroPlugin`

src/runtime/internal/database.client.ts
=> fix(client-database): prevent concurrent initialization

src/runtime/internal/connectors/bunsqlite.ts
#3118 
Bundler decided to strip the code with polyfills. I guess it wasn't considered as module side effect 🤷‍♂️. Moving this code to an exported function will fix this
=> fix(bunsqlite): polyfills not being loaded

src/runtime/internal/database.client.ts
=> fix(client-database): separate db init from collection dump fetch

docs/package.json, pnpm-lock.yaml, src/features/llms/runtime/server/content-llms.plugin.ts
=> chore: upgrade `nuxt-llms`

src/utils/content/index.ts
=> chore(utils): removed duplicated lang

.github/workflows/ci.yml, src/utils/content/index.ts
=> fix(module): load custom transformers with jiti

docs/content/docs/6.deploy/1.server.md
https://github.com/nuxt/content/issues/3248
Glibc 2.29 is required for a Server deployment when using sqlite database.
=> dcos: add environment requirement in server deployment

src/runtime/presets/cloudflare-pages/database-handler.ts
=> fix(cloudflare): load sql dump from assets

docs/content/docs/2.collections/1.define.md
Noticed a small typo in `nuxt/content` docs -- sending this patch to fix it.
=> docs: minor typo in nuxt/content documentation

docs/content/blog/v3.md
Fixed a minor typo in nuxt/content V3 announcement post.
=> docs: fixed minor typo in V3 announcement blog-post

src/runtime/internal/preview/collection.ts, src/runtime/internal/preview/compatibility.ts, src/runtime/internal/preview/files.ts
=> fix(preview): handle collection search with prefixed sources

src/module.ts, src/utils/database.ts
Prevent `require` is not defined exception
=> fix(module): check modules existence using `import`

docs/content/docs/1.getting-started/4.migration.md, docs/content/docs/6.deploy/5.vercel.md, docs/content/docs/6.deploy/7.aws-amplify.md, docs/content/docs/8.studio/1.setup.md
- **docs/content/docs/1.getting-started/4.migration.md**:
+ Fix spelling of `excldue` to  `exclude`
+ Fix spelling of `patter ` to  `pattern `
- **docs/content/docs/6.deploy/5.vercel.md**:
+ Change spelling of `Execeute` to `Execute`
- **docs/content/docs/6.deploy/7.aws-amplify.md**,
- **docs/content/docs/6.deploy/5.vercel.md**,
- **docs/content/docs/8.studio/1.setup.md**:
+ Change sentence structure slightly for clarity and consistency with how the other hosting providers sections are written.
- **docs/content/docs/8.studio/1.setup.md**:
+ Change spelling of `edition` to `editing`, as the prior didn't appear to fit. Though I could be wrong here.
=> docs: fix a few spelling issues and misc changes for clarity

docs/content/docs/3.files/1.markdown.md
Updated query used to include `/blog` prefix.
The original `/foo` path query should not be able to return a result.
=> docs: update not working markdown doc on querying blog collection

docs/content/docs/5.components/2.prose.md
None
Fixed an incorrect image path in the design-kit documentation.  
This change ensures the image displays properly in the rendered content.
=> docs: fix design-kit image path

src/module.ts
=> fix(module): ignore files in content folder in nuxt building

docs/content/docs/4.utils/2.query-collection-navigation.md, package.json, playground/components/ContentPage.vue, playground/content/1.real-content/index.md, src/runtime/utils/index.ts, test/unit/utils.test.ts
=> feat: add `findPageBreadcrumb`, `findPageChildren` and `findPageSiblings` utils

src/utils/dev.ts
resolves https://github.com/nuxt/content/issues/3410
=> fix(dev): support extension patterns like `**/*.md`

src/types/query.ts
=> feat: support `<=` and `>=` sql operators

src/utils/database.ts
=> fix: check for sqlite connector only if database type is sqlite

docs/content/docs/6.deploy/2.serverless.md
Azure Static Web Apps has the same architecture as AWS Lamda where `tmp` is the only writeable folder in the application
=> docs: extend tip for azure static web apps

package.json
resolves https://github.com/nuxt/content/issues/3538
=> fix: remove `zod` and `zod-to-json-schema` from optional deps
