nuxt/content

types/index.d.ts
It's possible that we may know what kind of data will be returned by the fetch method. So it would be useful to be able to edit the type of the information returned.
=> feat: support custom return types by the fetch method

docs/content/en/configuration.md, docs/content/en/fetching.md, example/content/products/jean.json, example/content/products/shirt.json, example/content/products/short.json, example/content/products/tshirt.json, example/nuxt.config.js, example/pages/products/index.vue, lib/database.js, lib/index.js
=> Nested properties

docs/content/en/advanced.md
As discussed in issue #82 with @philipithomas and @Atinux, this PR adds an example of integration between `@nuxt/content` and the Nuxt.js feed-module `@nuxtjs/feed`.
=> Add feed-module integration in documentation

lib/query-builder.js, test/module.test.js, test/plugin.test.js, test/server.test.js
=> fix: avoid date mismatch with API

lib/index.js
This should fix #52 by building the fetch URI using publicPath and router.base
=> use router basepath in client plugin

docs/content/en/writing.md, example/components/MovieInfo.vue, example/content/markdown.md, example/plugins/components.js, lib/parsers/markdown/compilers/json.js, lib/templates/nuxt-content.js, test/component.test.js, test/fixture/components/AppLayout.vue, test/fixture/content/vue-component.md, test/fixture/pages/_slug.vue
Fix #48
This PR modifies the JSON serializer to include the `content` AST from `template` tags and use it to create the [`scopedSlots` property](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments) for the `createElement` function. Due to parser limitations, the content cannot use templating nor [slot props](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots).
This PR also updates the documentation and example to illustrate this feature.
I'm still working on the tests.
=> Content distribution via templates and slots

example/content/yml.yml, example/pages/index.vue, lib/database.js, test/fixture/content/formats/yml.yml
The `.yml` extension for YAML is pretty popular from what I've seen. Perhaps it's partially because it's pretty often used in DevOps tools? 
Tried to search around for a consensus regarding this, but seems like there are avid supporters on both sides. The [YAML official site](https://yaml.org/faq.html) does mention to use `.yaml` when possible as pointed out when I was googling about it, but FWIW [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/) that does similar thing with nuxt/content also supports both `.yml` and `.yaml` extensions so I figured no harm in adding this. 
Tested this in the example project as seen in the commit and it works.
=> feat: add .yml support for YAML

docs/content/en/configuration.md
add missing install instructions for prism-themes to work
=> docs: (en) install prism themes

lib/parsers/markdown/compilers/json.js
This pull request updates the nuxt-content JSON parser to properly handle anchor tags which are missing an `href` attribute. Here is an example of a Markdown file which triggers the issue:
```markdown
---
title: Repro
---
<a name="foo"></a>Hello, world
```
The problem is that [this line](https://github.com/nuxt/content/blob/c5a11fc166fdec2d5cd4cbcc6880917ff861c047/lib/parsers/markdown/compilers/json.js#L16) crashes, since there is no `href` attribute. This pull request changes the behavior to gracefully handle situations like this.
I did not add any tests, since I felt this was a very minor change. If a test is desired, I can add one.
=> fix: Properly handle anchor tags without href fields

lib/middleware.js, lib/query-builder.js, lib/templates/query-builder.js, test/fixture/content/articles/build-dev-to-clone-with-nuxt-new-fetch.md, test/fixture/content/articles/introducing-smart-prefetching.md, test/fixture/content/articles/nuxtjs-from-terminal-to-browser.md, test/fixture/content/articles/understanding-how-fetch-works-in-nuxt-2-12.md, test/plugin.test.js, test/server.test.js
Use `compoundsort` instead of `simplesort` to handle sorting on multiple fields.
=> fix: use compound sort

lib/templates/nuxt-content.js
Resolves #247. 
Fix array props rendering of JSON AST to HTML.
=> fix: join array props

docs/content/en/writing.md, lib/database.js
Resolves: #252 
This stems from the linked issue, but I did also thought about this a while ago when considering to retain the datetime if I'm migrating the posts to nuxt/content. 
I have mentioned that the `createdAt` and `updatedAt` properties can be overrided in the docs [over here](https://github.com/nuxt/content/pull/254/commits/cbc006807d7f88f7b438d5f14f91e2b65d17b62f#diff-f520622309ad3e5bd5578a5b42164b37R31).
I'm not particular sure how we can add tests for this since the original createdAt & updatedAt of the files can be different if I make a new fork of the repo. With that said, I did do some tests myself and here are the test results:
|value in content/document|generated value when fetching|
|---|---|
|2019-02-10|2019-02-10T00:00:00.000Z|
|20x19-02-10|Falls back to original …
=> Allow override for createdAt and updatedAt properties

lib/index.js, lib/templates/plugin.client.js
fix #244. Adding globalName as options into plugin.client.js
=> fix: 244 pass globalName to plugin client to make sure it works

lib/query-builder.js
Ensure `path` and `extension` keys on dev mode when using `.only()` and `.without()` methods.
=> fix: ensure `path` and `extension` on dev mode

lib/parsers/markdown/index.js
Fixes table of contents generation with nested `code` in headings.
=> fix: improve toc heading parse

lib/utils.js, test/options.test.js
Functions in configuration are meant to allow merging default values. Now, functions are only executed if the value already exists in the configuration.
When using `extendParser` with a function `'.txt': (file) => ({ body: file })`, the function was executed.
=> fix: prevent options merging fn exec without default value

lib/templates/nuxt-content.dev.vue
Adds `shift` and `shift+tab` events on textarea in live edit mode.
=> feat: handle textarea tab / shift tab events

packages/content/lib/index.js
Instead of always ignoring the `content` dir for `nuxt generate`, the module should take config changes into account as well.
=> fix(ignore): comply with possible custom dir

packages/theme-docs/src/components/global/app/AppHeader.vue, packages/theme-docs/src/components/global/app/AppLangSwitcher.vue, packages/theme-docs/src/layouts/default.vue
Some Tailwind classes are present targeting same selectors. I've made a best-guess as to which you wanted to be in effect (based around which styles were overriding my browser). Please feel free to correct!
=> fix(theme-docs): remove duplicate tailwind classes

packages/theme-docs/src/store/index.js
Where a GitHub release name or tag includes the phrase `Release ` this will be removed. This shortens the rendering of the release in the header and on the releases page. Although a breaking change I can't imagine that this would be undesirable behaviour, but I'm happy to do some additional checking if it's felt that would be better.
Note that there is still the issue of some duplicated content:
It would be possible to address the issue of duplicated content and/or only adjust the release name if a `release-it` project is detected, if desired.
=> feat(theme-docs): support `release-it` default release syntax

docs/content/en/themes-docs.md, packages/theme-docs/src/components/global/app/AppGithubLink.vue, packages/theme-docs/src/plugins/init.js, packages/theme-docs/src/store/index.js
Not everyone will be preparing PRs against `dev`. It may be directly against `main` or against another branch. This PR allows customising this in settings (or automatically fetching the branch from GitHub). It defaults to `dev`, although this will be a breaking change in the (unlikely) case that users *prefer* a diff against `dev` even though they actually have a different default branch.
=> feat(theme-docs): allow customising default branch

packages/content/templates/plugin.static.js, packages/content/templates/plugin.static.lazy.js
=> fix(content): options were not forwarded in plugin static lazy

docs/nuxt.config.js, packages/theme-docs/src/index.js
The `generate` property with default routes to `['/']` and fallback needs to be defined almost everytime for documentation, so we moved it to the theme by default.
=> feat(theme-docs): add default `generate` property in config

package.json, packages/content/templates/nuxt-content.js, packages/content/test/component.test.js, packages/content/test/fixture/content/html.md
Fix props rendering in `nuxt-content` component.
The issue is in the `nuxt-content` component when rendering the AST tree with Vue.js, specific prop needed to stay in camelCase when others needed to be transformed back to kebab-case.
To fix #139, we forced `camelCase` props to kebab-case to ensure `ariaHidden` was rendered as `aria-hidden`. But then with #309, `<video autoplay ...>` was transformed to `{ autoPlay: true }` in the tree (HAST spec, see also [property-information code](https://github.com/wooorm/property-information/blob/main/lib/html.js#L41)) and then rendered to `auto-play` because of the module forcing kebab-case.
To transform markdown to AST, we use `remark` and `rehype`, to handle embedded HTML we use [rehype-raw](https://github.com/rehypejs/rehype-raw) which under the …
=> fix(content): use `property-information` to convert hast attributes

docs/content/en/snippets.md
Added automatic meta generation snippet
It helps quicker do the meta description without searching for it. Probably everyone had to do it so it is nice to have this snippet in the docs.
=> docs: add automatic meta generation snippet

packages/content/templates/nuxt-content.js
bug fix
I would like to use a v-bind to bind an object to a vue component but the obj constant here is preventing the v-bind key from being used.
=> Can't reassign obj on line 17 for v-bind key

packages/content/types/index.d.ts
Since PR #327 was merged, `tsc` throws the following error:
```
node_modules/@nuxt/content/types/index.d.ts:6:45 - error TS2307: Cannot find module 'node-csvtojson/v2/Parameters' or its corresponding type declarations.
6 import { CSVParseParam as csvOptions } from "node-csvtojson/v2/Parameters";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```
Probably `node-csvtojson` is a typo of `csvtojson`.
And, PR #327 forces you to add an empty `content` property in configuration file.
This PR fixes module name typo, and set `content` property as optional.
No need tests because this PR only changes typing.
=> fix(types): fix typing error

docs/content/en/themes/docs.md
`<alert>` component don't have `error` type, but `danger` instead :
https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/components/global/base/Alert.vue#L17
=> docs(theme): fix alert type values

packages/create-nuxt-content-docs/template/content/en/setup.md
doc was linking to old docs so changed it to use new docs link
uses the new docs instead of the old docs by replacing the link
=> fix: use new docs link

packages/theme-docs/src/components/global/base/Alert.vue
`.alert-content` in dark mode has too many styles.
=> fix(theme-docs): remove useless alert styles

packages/theme-docs/src/components/global/app/AppToc.vue, packages/theme-docs/src/tailwind.config.js
I propose to replace the transform transition by a padding transition on TOC items.
Current behavior with transform transition:
Behavior with padding transition:
=> fix(theme-docs): improve TOC hover

packages/theme-docs/src/components/global/base/Alert.vue
In dark mode, the syntax highlighting inside alert does not work well.
Before:
After:
=> fix(theme-docs): fix syntax highlighting in alert

packages/content/lib/index.js, packages/content/package.json, packages/content/templates/plugin.static.js
Fix issue when using app in SPA mode. The DB wasn't call correctly (using a `Date.now()` which makes unusable offline mode)
It resolve #229 ! Using a env in the runtimeConfig and passing it to the static plugin, the value is the same during the app is alive but change when there is a new build !
Maybe I can use a key generation but don't kwon how !
=> fix(content): Offline mode

packages/create-nuxt-content-docs/template/content/en/index.md
By adding a height/width, modern browsers can reserve space for the responsive image.
https://deltener.com/blog/how-to-fix-image-jank-to-improve-your-cumulative-layout-shift-score/
=> feat: reduce page jank

docs/content/en/advanced.md, example/content/json.json, example/nuxt.config.js, packages/content/lib/index.js
Add `database` as second argument for beforeInsert hook to simplify extending document, see https://content.nuxtjs.org/advanced#contentfilebeforeinsert
=> feat: add database as second argument for beforeInsert

docs/content/en/themes/docs.md, packages/theme-docs/src/components/app/AppGithubLink.vue, packages/theme-docs/src/store/index.js
This option can be used to override the default `docs` dir used in the "Edit this page on GitHub" link if your project lives in a different directory.
Resolves #455, resolves #430.
=> feat(theme-docs): add `defaultDir` options

packages/theme-docs/src/tailwind.config.js
Tailwind v1.8.0 introduced new layers purge mode which will be the default in v2.0, [as mentioned in the docs here](https://tailwindcss.com/docs/upcoming-changes#purge-layers-by-default). Quote from link:
> You should see an even smaller CSS file by default with the new layers mode enabled, and shouldn't see any negative consequences unless you were deliberately relying on the fact that Tailwind was previously not purging the base or components layers by default.
thus I didn't see anything breaking as mentioned by the quote, while reaping the benefit of lower filesize. Here is the comparison of before and after I manually added **purgeLayersByDefault** to the `tailwind.config.js` file:
_Note: both `original-docs` and `new-docs` are totally new projects created using `yarn create …
=> chore(theme-docs): add tailwindcss purgeLayersByDefault future flag

packages/content/types/index.d.ts
According to this code:
https://github.com/nuxt/content/blob/711913c4772a9aad442f093eb4ddc822771e873f/packages/content/lib/utils.js#L46-L48
it should accept options with `[<plugin-name>, <options>]` syntax.
=> fix(types): remark plugins and rehype plugins should accept options in array syntax

packages/theme-docs/src/assets/css/main.css
Fixes #463.
As the issue highlighted, the filename will intersect with the first line of a code block. Below is a sample screenshot, one with no filename and the one with filename exhibits this issue:
_Note: They may not look super intersecting like the one show in the issue, but it's because only characters with long tail like "q", "p" or "g" are the worst offender._
The obvious fix is to add a top padding to code blocks, but this will make code blocks without filename look awkward with top gap. This is the reason why I used the `+` operator in `.filename + pre[class*="language-"]` which **will only target the `pre` tag if there is a div with `.filename` class above it.** The resulting fix is shown in the screenshot below:
Notice how the top code block has equal top and bottom padding …
=> fix(theme-docs): fix code block's filename style

docs/content/en/integrations.md
- [x ] Bug fix (a non-breaking change which fixes an issue)
The existing documentation for integrating with nuxt/feed does not work when statically generating pages. Also, it does not include a process for getting all of the content for the content field of the feed. This change will provide that missing information. This change also adds a process for integrating with nuxt/sitemap. Closes #425 Closes #386
=> docs: updated integrations with more information #425 #386

docs/content/en/themes/docs.md, packages/create-nuxt-content-docs/src/saofile.js, packages/create-nuxt-content-docs/test/cli.test.js, packages/theme-docs/src/components/app/AppGithubLink.vue, packages/theme-docs/src/components/app/AppHeader.vue, packages/theme-docs/src/components/app/AppNav.vue, packages/theme-docs/src/store/index.js
This PR implements #439, and lets us fetch repositories hosted on GitHub Enterprise, whose API has other domain than `api.github.com`.
I defined a Vuex getter `githubUrls` that returns an object whose values are full urls to get data of repository and its releases.
In addition, I modified related part of docs and SAO prompts.
First, I added a test case to check whether it creates files correctly when developer assign full url of repository instead of `owner/repo` string.
Second, I ran `yarn test` in the project root and all the tests were passed.
First, I ran `yarn link` for all the packages (`@nuxt/content`, `@nuxt/theme-docs`, and `create-nuxt-content`). 
Second, I ran the linked `create-nuxt-content` to get `theme-docs` files. 
Third, I replaced the installed `@nuxt/theme-docs` with my …
=> feat: support github custom domain

packages/theme-docs/src/store/index.js
Fixing an issue in the store that was providing the incorrect URL for the Github repository to render in the navbar
This issue solves a problem that was causing a Github repository URL to include a /repos/ portion in the URL, which lead to a Github 404 page. The links in the navbar will not be correct.
=> fix(theme-docs): fixed incorrect Github URL for navbar

docs/content/en/themes/docs.md
I found that my PR (#458) was [released as a part of `v0.6.0`](https://github.com/nuxt/content/releases/tag/%40nuxt%2Fcontent-theme-docs%400.6.0), so it would be kinder to add version badge to the according parts of doc.
By the way, I also found that my PR included a typo, which was reported by @antho1404 as #492, and fixed by @DavidTParks as #489. The bug-fix was released as a part of `v0.6.1`. Thank you folks. I will be more careful when submitting PRs. 🙏 🙇
=> docs: add version badges for features of #458 

docs/content/en/writing.md, example/content/articles/build-dev-to-clone-with-nuxt-new-fetch.md, example/content/articles/introducing-smart-prefetching.md, example/content/articles/nuxtjs-from-terminal-to-browser.md, example/content/articles/understanding-how-fetch-works-in-nuxt-2-12.md, example/content/authors.json, example/pages/articles/_slug.vue, packages/content/lib/database.js, packages/content/test/fixture/content/authors.json, packages/content/test/server.test.js
This PR will allow to create `.json` files with arrays at the root:
```json
[
{
"name": "Sébastien Chopin",
"slug": "atinux"
},
{
"name": "Krutie Patel",
"slug": "krutiepatel"
},
{
"name": "Sergey Bedritsky",
"slug": "sergeybedritsky"
}
]
```
will insert:
```json
[
{
"name": "Sébastien Chopin",
"slug": "atinux",
"dir": "/authors",
"path": "/authors/atinux",
"extension": ".json"
},
{
"name": "Krutie Patel",
"slug": "krutiepatel",
"dir": "/authors",
"path": "/authors/krutiepatel",
"extension": ".json"
},
{
"name": "Sergey Bedritsky",
"slug": "sergeybedritsky",
"dir": "/authors",
"path": "/authors/sergeybedritsky",
"extension": ".json"
}
]
```
> This PR allows `slug` override.
=> feat(content): handle json arrays

packages/content/templates/editor.vue
I often use tab key to composition string from the suggested clauses with IME, but using on editor.vue occurs unexpected behavior.
This PR is to avoid tab key handling on the editor.vue during text composition session.
|  Before  |  After  |
| ---- | ---- |
|  ![before](https://user-images.githubusercontent.com/2783737/94357627-838caa00-00d5-11eb-89ed-b5e96942731d.gif) |  ![after](https://user-images.githubusercontent.com/2783737/94357631-88e9f480-00d5-11eb-9dde-00f1a0d14b51.gif)  |
Testing event handling is a bit hard..., but l can try to add it so please let me know if it's needed.
=> fix(content): fix tab key handling of editor component with IME

packages/content/types/query-builder.d.ts
The type for `QueryBuilder#fetch` (introduced in https://github.com/nuxt/content/pull/444) is defined as a synchronous method. However it is not, because it returns a Promise.
=> fix: Incorrect type for fetch which returns a promise

packages/content/package.json
Include all typescript files on build. This will solve the problem that parsers are not included in the build.
In #444 I created a PR for extra types. By mistake I didn't add these files to the package.json for build process. This means in test environment it works but after a build the parser types are not included. I believe including all `*.d.ts` files in the package.json will resolve this problem.
=> fix: Included types folder in files

docs/content/en/themes/docs.md
To have it link to your repo with no subdirectory
Just a simple docs change to add clarity as it took me a while to figure out hot to get the link to work using the base theme
=> docs: specify that you can have an empty string

docs/content/en/themes/docs.md, packages/theme-docs/src/components/global/base/List.vue
Improve `<list>` component to default to `primary` color (avoids breaking actual docs) and allows to override the icon.
=> chore(theme-docs): improve list component

packages/theme-docs/src/layouts/default.vue, packages/theme-docs/src/layouts/single.vue, packages/theme-docs/src/store/index.js
When adding a trailing slash to `url`  in `content/setting.json`, the preview on Twitter was broken, this avoid this situation.
I also added a warning if the user forget to fill the url in `content/setting.json`.
=> fix(theme-docs): twitter preview when trailing slash on url

docs/content/en/advanced.md
None of above.
Argument of `content:file:beforeParse` hook is explained as `data`, but it is written as `file` in both the sample code and the internal code. So, I changed the term `data` to `file` for consistency.
Since this is just a change on text in doc, unit/e2e testing is not needed, is it?
=> chore(theme-docs): unify term in official docs

packages/content/lib/ws.js
=> fix: set header to empty string if undefined

packages/content/types/index.d.ts
Fix #600.
I forgot to add types of `options.markdown.tocDepth` and `options.markdown.tocTags` ([link](https://github.com/nuxt/content/blob/b2f45db0b16ecdf21981f6eff0afdc851829ccbe/packages/content/lib/utils.js#L36-L54), [link](https://github.com/nuxt/content/blob/b2f45db0b16ecdf21981f6eff0afdc851829ccbe/packages/content/lib/utils.js#L87)).
There is no tests for types, as far as I see.
By the way, the tests fails in highlighter in the latest commit of `dev` branch of `nuxt/content` (b2f45db).
Since this branch is created from `dev`, PR CI will fail too.
=> fix(content): add missing types

packages/content/templates/nuxt-content.js
There was a bug in named slot rendering: if there was more than one prop in the slot and name was not the first one, it would be considered nameless.
=> Fixed a bug in named slot rendering

docs/content/fr/examples/basic.md, docs/content/fr/examples/docs-theme.md, docs/content/fr/examples/tailwindcss-typography.md, docs/content/fr/integrations.md, docs/content/fr/snippets.md, docs/content/fr/themes.md, docs/content/fr/themes/docs.md
Hi 👋 
There is several missing pages about the french documentation particularly for creation of docs themes 😀
I added the missing pages and examples like : 
- integrations.md
- snippets.md
- theme/docs.md
- examples/tailwindcss-typography.md
- examples/docs-theme.md
- examples/basic.md
=> docs: french translation

packages/content/lib/database.js, packages/content/test/fixture/content/1.0/index.md, packages/content/test/server.test.js
Currently, it's impossible to create a directory into `content` which contains dot due to replace extension of normalize path function.
Resolves: #640
=> chore: allow directories name to contain a dot

packages/content/templates/nuxt-content.js
Properly treat falsy values in context
Previously, if a component's attribute referenced a value in context and that value happened to be falsy, it was ignored, which lead to an error. See this [sandbox](https://codesandbox.io/s/nuxt-content-reactivity-issue-forked-lkjyy?file=/content/en/index.md) for reproduction.
This PR fixes this problem.
This was discovered while researching #519
=> fix: properly treat falsy values in context

packages/theme-docs/src/components/app/AppHeader.vue
Take care of trailing slashes enabled in the nuxt configuration. Currently, it gives 404 not found page.
Basically, when trailing slashes enabled in nuxt configuration releases page doesn't load:
```js
router: {
trailingSlash: true,
},
```
You can check it here http://haraka.github.io/ click on version and it gives `This page could not be found`, however complete refresh of a page works fine.
=> fix(theme-docs): correct releases link

docs/content/en/fetching.md
The current `new Date(2020)` example seems to suggest something about the year 2020, which is confusing, especially to newcomers using the documentation.
Therefore I propose to show a more meaningful example date (date of this repo's first commit), in a more common format (passed to Date constructor as string), instead of 2020 ms since Unix Epoch (passed to Date constructor as int).
=> docs: change from epoch-based to 'yyyy-mm-dd'-based date

docs/content/en/themes/docs.md, packages/theme-docs/src/components/app/AppNav.vue, packages/theme-docs/src/index.js
It is explained in documentation that `category` in front-matter is optional. However, theme docs renders the category header in AppNav component regardless of existence of it.
- If `category` is completely not defined in front-matter, theme docs renders `undefined` as a uppercase text.
- If `category` is set as an empty string in front-matter, theme docs renders an empty _p_ element with margin-bottom.
[Reproduction Link (CodeSandbox)](https://codesandbox.io/s/gifted-torvalds-kghq0?file=/content/en/about.md)
With my PR, `category` in front-matter is validated in `content:file:beforeInsert` hook, and is set as an empty string if it's falsy or not a string. Coercion to an empty string is for its type to match [that described in documentation](https://content.nuxtjs.org/themes/docs#front-mat …
=> fix(theme-docs): remove redundant header

packages/content/lib/database.js
This PR adds a second param for custom parsers that is an object (for future extend-ability) with the file path.
Here is my use case:
I'm building a photography portfolio website where I want to drop images in the content folder. I have a custom parser that extracts metadata from the jpg. Sadly I can't get the utf-8 read file content to parse correctly on any of the packages I have found on npm. Most of them just take the file path and handle the reading themselves.
=> feat(content): add path for custom parsers

packages/content/parsers/markdown/handlers/code.js
I think #621 breaks lang parsing in codeblock when it contains other meta that is not filename. This causes highlightjs not to work as expected. When codeblock contains other meta that is not filename, it should not break lang parsing in utils.parseThematicBlock. Making it difficult to write and use remark plugins that contains meta.
||For Reference|
|-|-|
| Markdown | <img src="https://user-images.githubusercontent.com/4266087/102744656-50d11580-4395-11eb-8393-c25c6b16c682.png" width="60%"> |
| Currently  | <img src="https://user-images.githubusercontent.com/4266087/102745212-76125380-4396-11eb-879c-7fa7d0a6a30f.png" width="60%"> |
| **Expected** | <img src="https://user-images.githubusercontent.com/4266087/102745332-ae199680-4396-11eb-9d83-6306bccfe148.png" width="60%"> |
=> fix(content): codeblock parse lang should support other meta

packages/content/types/index.d.ts
in vuex with typescript `this.$content` will not work
example code:
```ts
export const actions: ActionTree<AppState, {}> = {
// ....
async loadData({ commit }) {
const data: IData[] = (await this.$content(this.$i18n.locale, "data").fetch().catch(console.error)) as any;
if (data) {
commit("UPDATE_DATA", data);
}
}
};
```
it should be typed as 'contentFunc'
=> fix(types): change types

docs/content/en/fetching.md, docs/content/fr/fetching.md, packages/content/lib/query-builder.js
Passing an empty string  as query value will avoid triggering a search to allow optional chaining such as this:
```js
this.total = (await this.$content('people')
.search('')
.only([])
.fetch()).length
```
Docs have been updated in FR & EN. JA & RU update necessary.
=> feat(content): Optional search parameter

packages/content/parsers/markdown/index.js, packages/content/test/fixture/content/toc-dom-depth-2.md, packages/content/test/options.test.js
Currently Nuxt Content uses only top level elements to generate table of content therefore TOC will not generate for documents which wrapped inside a tag.  
Originally issued here: https://www.github.com/nuxtlabs/docus/issues/21#issuecomment-776078940
=> fix: use top 2 level of nodes to generate toc

docs/content/en/snippets.md
Fixes #756, where triple back ticks to close code block are missed.
Now _Snippet_ page is broken.
It's just my bad. 🙏 
| Current Production | This PR |
| :---: | :---: |
|<img width="100%" alt="Screen Shot 2021-02-10 at 22 19 38" src="https://user-images.githubusercontent.com/16436160/107515302-30337800-6bee-11eb-9600-ba8f7fc84021.png">|<img width="100%" alt="Screen Shot 2021-02-10 at 22 20 17" src="https://user-images.githubusercontent.com/16436160/107515315-33c6ff00-6bee-11eb-8742-466ac981b5d9.png">|
As shown above, I checked UI in my local.
=> docs: fix markdown syntax

packages/content/lib/database.js, packages/content/parsers/markdown/handlers/code.js
…ighlighter
Regression from #755. Reproducable on nuxt/nuxtjs.org:
```
WARN  Could not parse ./content/en/blog/moving-from-nuxtjs-dotenv-to-runtime-config.md: Cannot read property 'match' of null                                                    @nuxt/content 15:50:42
```
=> fix(content): handle empty lang

packages/content/lib/database.js
Resolves: #890
when run `npx nuxt webpack` ，termianl log show show `1.1 sconds` ,not `1,1 sconds`
=> fix: terminal time log information display error

src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/server/api/navigation.ts, src/runtime/server/api/query.ts, src/runtime/server/params.ts, src/runtime/server/storage.ts, src/runtime/utils/json.ts, test/basic.test.ts, test/features/regex.ts
Usage:
```ts
queryContent().where({ slug: /^\/cats/ }).find()
```
=> fix: encode regex in query params

packages/content/templates/nuxt-content.js
The `property-information` package does not export a default object and thus `import info from "property-information"` returns `undefined`, resulting in the content module failing to render markdown files.
I was trying to use the `nuxt-content` component to display a fetched markdown file, but it failed with an error. I followed the code and discovered that the import statement used in `nuxt-content.js` is incorrect. It tries to import a default `info` object from the property-information package, but there is no default object exported. Instead, all members are exported individually.
The fix involves using `import * as info from...` instead `import info from...`
I have run tests and they all passed.
=> fix: invalid default import from property-information

packages/theme-docs/src/i18n/vi-VN.js
Adding i18n/vi-VN.js for Vietnamese locale
=> fix(theme-docs): Add  vi-VN.js for Vietnamese

docs/content/en/writing.md
docs content tweak
Props of Vue component  in Markdown content need to use kebab name casing. This PR adds this caveat to the the documentation.
=> docs(content): add Vue components prop casing caveat

src/runtime/server/api/cache.ts, src/runtime/server/api/navigation.ts, src/runtime/server/api/query.ts, src/runtime/server/index.ts, src/runtime/server/storage.ts
Change server query composable interface and rename it to `serverQueryContent` #1067
=> fix(server): rename `queryContent` to `serverQueryContent`

src/runtime/server/transformers/json.ts, src/runtime/server/transformers/yaml.ts, test/features/parser-json.ts, test/features/parser-yaml.ts
Reverts nuxt/content#1095
After discussions we stated that merging data objects would not be the pattern supported in v2.
This is a breaking change from v1 and will stay as is for consistency concerns over parsed content objects.
=> Revert "feat!: update json & yml transformers"

docs/content/1.guide/2.displaying/4.typescript.md
As shown in https://github.com/nuxt/content/issues/1057, the interface provided to `queryContent` must extend `ParsedContent`, which is not the case right now.
=> fix: code example

src/runtime/components/Markdown.ts
Changing vDOM nodes directly will lead to unexpected behaviors in future renders. Instead of manipulating existed nodes we need to create new nodes.
=> fix(`<Markdown>`): prevent vDOM manipulation

src/runtime/query/match/utils.ts, test/features/query/query.test.ts
=> fix(query): handle nullable fields in sort

src/runtime/components/ContentQuery.ts, src/runtime/composables/query.ts
When using `nuxt generate` and deployed on `surge.sh`, a trailing slash is added automatically, making a new request on client-side with a different query hash. Removing the trailing slash fixes it.
=> fix: remove trailing slash to support nuxt generate

docs/content/4.api/2.composables/1.query-content.md
Missing single quote in the `findSurround` example.
=> docs: Update 1.query-content.md

docs/content/3.guide/2.displaying/1.rendering.md
None, as this is a trivial typo-ish problem. 🙂 
The link to Nuxt 3's catch-all route documentation points to an internal path, but the correct path is naturally located under the v3.nuxtjs.org.
=> docs: correctly link to catch-all documentation

docs/content/2.get-started.md
I just added the `--shamefully-hoist` argument because otherwise when we launch a fresh project, we encounter the following errors: 
```
ERROR  Failed to resolve import "ufo" from "...". Does the file exist?
ERROR  Failed to resolve import "vue" from "...". Does the file exist?         
```
Because these dependencies are not defined in the package.json
See : https://pnpm.io/fr/npmrc#shamefully-hoist
=> docs: add `--shamefully-hoist` argument to pnpm install

docs/content/3.guide/2.displaying/2.querying.md
In the current example, route is being destructured to only use the path property, so I've replaced `route.path` with just `path` to not get a `route is not defined` error
=> docs: fix querying example route is not defined

docs/content/3.guide/2.displaying/1.rendering.md, docs/content/3.guide/3.migration/1.from-v1.md
Source code reference provided in [rendering guide](https://content.nuxtjs.org/guide/displaying/rendering#contentrenderer-) gives 404 error, so update to correct path
=> docs: correct path of ContentRenderer source code

src/runtime/components/ContentQuery.ts
Generate cache key based on component props to prevent conflict between different usages. (For example using `ContentDoc` and `ContentList` with same path)
=> fix(ContentQuery): generate cache key based on props

src/runtime/query/match/utils.ts, test/features/query/query.test.ts
=> fix(sort): convert Date to ISO string

src/module.ts
n/a
Small change to type comments of the `ModuleOptions` interface. Typo (on navigation property) showed:
```js
/**
* Enable/Disable navigation.
*
* @defaul {}
*/
```
Corrected to:
```js
/**
* Enable/Disable navigation.
*
* @default {}
*/
```
=> docs:fixing navigation comments re: default value

docs/public/_redirects
This PR removes the `configuration/` entry in redirects to avoid a bad redirect.
=> docs(redirects): remove configuration redirect

docs/content/4.api/4.advanced.md, src/runtime/server/transformers/index.ts, test/basic.test.ts, test/features/parser-hooks.ts, test/fixtures/basic/addons/nitro-plugin.ts, test/fixtures/basic/nuxt.config.ts
#1119
Introduce two hooks to manipulate contents before/after parsing.
=> feat: call hooks before and after parse

src/runtime/composables/query.ts, src/runtime/server/storage.ts, test/basic.test.ts, test/fixtures/basic/content/_partial/content (v2).md
Escape special chars in the path to find exact matches in contents.
=> fix(query): escape special chars in path

src/runtime/server/api/navigation.ts, test/features/navigation.ts, test/fixtures/basic/content/navigation-disabled.md
The [documentation](https://content.nuxtjs.org/guide/displaying/navigation) says 
> Set navigation: false in the [front-matter](https://content.nuxtjs.org/guide/writing/markdown) of a page to exclude it in fetchContentNavigation() return value.
However, it doesn't work. I couldn't find any logic for excluding this. The Example on the page is even showing the wrong data.
This change properly filters out the pages with this setting from the navigation query.
=> fix(navigation): allow navigation opt-out with `navigation: false`

src/runtime/query/query.ts, src/runtime/types.d.ts
Allows type hinting on the keys for `only` and `without` as well as augmenting the result which will either include or exclude the provided keys from the IntelliSense respectively.
=> feat(types): provide augmentations for `only` and `without`

playground/content/real-content/content.md, src/module.ts, src/runtime/server/transformers/csv.ts, src/runtime/server/transformers/json.ts, src/runtime/server/transformers/markdown.ts, src/runtime/server/transformers/path-meta.ts, src/runtime/server/transformers/shiki.ts, src/runtime/server/transformers/yaml.ts, src/runtime/types.d.ts
The key is spelled incorrectly, as someone who is adding a custom transformer I'd prefer not to have misspelled keys in my code. 
BREAKING CHANGE: custom transformers should rename key `extentions` to  `extensions`
=> refactor!: spell `extensions` correctly

src/runtime/server/transformers/path-meta.ts, src/runtime/types.d.ts
- `_slug` is not used but is in the types, which is misleading
- full list of id types (`_type`, `_file`, `_extension`) are missing
- added types to the path-meta file to ensure stricter type adherence
=> fix(types): more accurately represent `ParsedContentMeta`

docs/content/3.guide/2.displaying/4.typescript.md, src/runtime/markdown-parser/index.ts, src/runtime/server/transformers/markdown.ts, src/runtime/types.d.ts
Add a Markdown specific parsed content schema, allowing end-users to build generics that have better type safety.
I did see https://github.com/nuxt/content/issues/1057, I'd presume we'd need a safer type for markdown files when that's built so this should help with that.
=> feat(types): expose `MarkdownParsedContent` for improved type generics

docs/content/4.api/1.components/3.content-navigation.md, package.json, src/runtime/components/ContentNavigation.ts, src/runtime/composables/navigation.ts, test/basic.test.ts, test/features/navigation.ts, test/fixtures/basic/pages/nav-with-query.vue
The `ContentNavigation` component is typed to only allow you to provide the query as `QueryBuilderParams`. The DX of this isn't great as everywhere else in the doc a `QueryBuilder` is used with `queryContent`.
This is especially annoying when you want to show the `ContentNavigation` with a simple path prefix, as the user has to then figure out regex.
The `fetchContentNavigation` already supports a `QueryBuilder`, so it's seems like this was the initial expectation of this prop anyway.
I've added an example to highlight the use case
=> feat(navigation): allow passing QueryBuilder or QueryBuilderParams in `fetchNavigation` or `<ContentNavigation>`

src/runtime/components/ContentQuery.ts
=> fix(ContentQuery): handle `null` data

src/runtime/query/match/utils.ts, test/features/query/query.test.ts
resolves #1235 
https://github.com/nuxt/content/blob/ede65e8337ca3eb597af95c17cfc609e4015238c/src/runtime/query/match/pipeline.ts#L46
When using `findSurround`, it is necessary to take into account that `null` are mixed in the pipeline data.
=> fix(query): surround and only cannot be used at the same time

src/runtime/server/storage.ts, test/basic.test.ts, test/fixtures/basic/content/with-'invalid'-char.md
=> fix(storage): warn & ignore files with invalid characters

src/runtime/query/match/index.ts, test/features/query/match.test.ts
resolves #1272
The current behavior of `$in` operator was wrong, because it tried to check equality between item and condition.
For example in this sample:
```
const item = { tags: ['foo', bar'] }
const cond = { tags: { $in: [ 'foo'] }
match(item, cond)
```
`$in` operator was checking if `'foo' === ['foo', 'bar']`. 
But the correct behavior for arrays is not equality check, it is `$contains` check.
=> fix(query): handle array fields in `$in` operator

src/runtime/plugins/documentDriven.ts
This PR should resolve issues reported from usage of documentDriven feature.
=> fix(document-driven): update documentDriven feature

docs/content/3.guide/1.writing/2.markdown.md, docs/content/4.api/1.components/1.content-doc.md, docs/content/4.api/2.composables/6.use-content-head.md, docs/package.json, docs/yarn.lock, playground/document-driven/content/0.index.md, src/module.ts, src/runtime/components/ContentDoc.ts, src/runtime/composables/head.ts, src/runtime/pages/document-driven.vue, src/runtime/plugins/documentDriven.ts, test/fixtures/basic/pages/bypass-head.vue
This PR adds `useContentHead(document: ParsedContent, to: RouteLocationNormalized = useRoute())` function.
It gives easy access to `<head>` binding in both `<ContentDoc>` and `documentDriven` features.
It is easily toggleable for `<ContentDoc />` via the new `head` props.
If you want to remove the binding from `documentDriven`, you can overwrite the default `[...slug].vue` page.
Documentation has been updated.
Also fixes the latest issues with documentDriven `path` errors. 😬
=> feat(use-content-head): add helper for <head> binding

docs/content/3.guide/1.writing/7.document-driven.md
=> docs: fix inline code block

src/module.ts
=> fix: remove _theme.yml fetch with doc driven by default

src/runtime/components/ContentRendererMarkdown.ts, src/runtime/plugins/documentDriven.ts
Preload component used content to prevent lazy loading and creating layout shifting.
However, using the async setup function in `ContentRendererMarkdown` causes a new issue.
=> fix(ContentRendererMarkdown): preload components used in content

src/runtime/markdown-parser/remark-mdc/micromark-extension/tokenize-span.ts, test/features/parser-markdown.ts
=> fix(markdown): attributes of span inside headings

src/runtime/plugins/documentDriven.ts
Similar to `useAsyncData` caching system, only on client-side, will save a loooot of requests for document driven mode.
=> feat(document-driven): add caching layer on client-side

docs/content-v1/en/3.community/1.snippets.md
Resolves #1318 
Fixes the id in the link to the surround function documentation (EN v1)
=> docs: fix the link-id for the surround EN v1 docs

docs/content/4.api/3.configuration.md
=> docs: missing `,`

docs/content/3.guide/1.writing/7.document-driven.md, src/runtime/plugins/documentDriven.ts, test/document-driven.test.ts, test/features/navigation.ts, test/fixtures/document-driven/content/no-surround.md, test/fixtures/document-driven/pages/disabled.vue, test/fixtures/document-driven/pages/no-surround.vue
Allow disabling/modifying document-driven 
```vue
<script setup>
definePageMeta({
documentDriven: false,
// Or if need content but no surround
documentDriven: {
page: true,
surround: false,
},
});
</script>
```
=> feat: disable document driven with route meta

docs/content/3.guide/3.recipes/1.sitemap.md
This changes the install command shown to conform with the rest of the documentation.
=> docs(sitemap): add `npm` and `pnpm` install script

package.json, src/runtime/components/ContentDoc.vue, src/runtime/components/ContentList.vue, src/runtime/components/ContentNavigation.vue, src/runtime/components/ContentQuery.vue, src/runtime/components/ContentRenderer.vue, src/runtime/components/ContentRendererMarkdown.vue, src/runtime/components/DocumentDrivenEmpty.vue, src/runtime/components/DocumentDrivenNotFound.vue, src/runtime/components/Markdown.vue, src/runtime/types.d.ts, yarn.lock
resolves #1358
Improve types of query builder. Add type for `where` conditions.
=> feat: improve where query types

docs/content/4.api/2.composables/1.query-content.md
#1176 
The breaking API change from #1176 is not reflected in the docs of `queryConten().sort()`. This PR fixes that.
=> fix: Updating documentation regarting queryConten().sort() descending sorting

src/runtime/transformers/index.ts
Do not register shiki transformer by default, it should register depending on `highlight` option.
=> fix(highlight): respect `highlight` option

src/runtime/components/Prose/ProseH2.vue, src/runtime/components/Prose/ProseH3.vue, src/runtime/components/Prose/ProseH4.vue
#1380
The `<NuxtLink>`s for the heading links are replaced by the HTML anchor element `<a>` to enable focusing on clicking on the link.
The focusing is not working with NuxtLink and as [this discussion](https://github.com/nuxt/framework/discussions/5561#discussioncomment-3007717) points out, can be replaced by the default HTML element.
=> fix(prose-components): use html anchor link in headings

docs/content/4.api/2.composables/2.fetch-content-navigation.md
The documentation was missing that `fetchContentNavigation()` has to be in a function:
```sh
[nuxt] [request error] [nuxt] [asyncData] handler must be a function.
at createError (./node_modules/h3/dist/index.mjs:196:15)  
at Server.nodeHandler (./node_modules/h3/dist/index.mjs:386:21)  
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This is also visible in the [example](https://content.nuxtjs.org/examples/navigation/fetch-content-navigation/)
=> docs: move fetchContentNavigation into function

src/module.ts
=> fix: support components/content in layers for extends

docs/components/content/ExampleTheTitle.vue, docs/components/content/MyButton.vue, docs/content/3.guide/1.writing/3.mdc.md, docs/content/4.api/1.components/5.markdown.md, docs/content/6.blog/1.announcing-v2.md, src/runtime/components/Markdown.vue, test/basic.test.ts, test/fixtures/basic/components/content/Alert.vue, test/fixtures/basic/components/content/TestMarkdown.vue, test/fixtures/basic/content/_partial/markdown.md
resolves https://github.com/nuxt-themes/alpine/issues/44
=> feat(`<markdown>`): support fallback default slot

playground/document-driven/content/0.index.md, src/runtime/pages/document-driven.vue, test/document-driven.test.ts
It should not return a Nuxt error but only set the 404 status code on SSR, when using the dd mode, you can create a `<DocumentDrivenNotFound />` component
=> fix(document-driven): Only set 404 status on SSR

src/module.ts
closes #1417, related to nuxt/framework#6382
In mutli layer setups the priority of the layers is wrong and needs to be reversed, so that `content` is on top
=> fix: make sure `components/content` is on top in layers

src/module.ts
=> feat: pre fetch contents on build

package.json, src/module.ts
resolves https://github.com/nuxt/content/issues/1422
An unreleased (and now reverted) change in kit template utils broke nuxt content briefly. This PR implements a TODO to use knitwork directly to generate import names.
=> fix: remove (now deprecated) template utils

src/utils.ts
Fix build issue on https://github.com/nuxtlabs/nuxt.com/pull/856
=> fix(pre-fetch): support github driver

docs/content/1.index.md, docs/content/8.playground.md, docs/content/9.content-v1.md, docs/layouts/blogpost.vue, docs/yarn.lock
=> docs: upgrade deps

docs/content/3.guide/5.migration/1.from-v1.md
Fixed typo: 'Convent' -> 'Content'
=> docs: fix typo 'Convent' -> 'Content'

docs/content/3.guide/1.writing/2.markdown.md
=> docs: excerpt

docs/content/4.api/1.components/2.content-renderer.md, src/runtime/components/ContentRendererMarkdown.vue, test/__snapshots__/basic.test.ts.snap, test/features/renderer-markdown.ts, test/fixtures/basic/components/content/CustomProseP.vue, test/fixtures/basic/content/_partial/custom-paragraph.md, test/fixtures/basic/content/index.md, test/fixtures/basic/pages/features/custom-paragraph.vue
=> feat: per-page components

src/module.ts
We introduced a fix in #1418 to reverse scan layers and regression of #1404. By calling `reverse()` we were mutating original `_layers` too causing whole layer scanning logic after content being broken.
=> fix: avoid mutating `_layers`

src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/utils/query.ts
resolves #1454
resolves #1281
Add `.json` extension to pre-rendered queries. 
The issue here is that `npx serve` with `-s` option, redirects all URLs (without extension) to `index.html` and therefore serving generated websites with `nuxi preview` return 404 for API routes.
In current state, `npx nuxi preview` and `npx serve -s .output/public` does not work and only `npx serve .output/public` works properly.
=> fix(prerender): add extension to prerendered queries

src/runtime/components/ContentRenderer.vue, test/features/renderer-markdown.ts, test/fixtures/basic/pages/features/slotted-content-renderer.vue
resolves #1459
Using the default slot in `<ContentRenderer>` did not affect rendered HTML when the content is a markdown file.  
This PR will prioritize the empty slot and the default slot.
=> fix(`<ContentRenderer>`): prioritize default slot

README.md
The first link to MDC syntax was pointing to nothing. It is now pointing at https://content.nuxtjs.org/guide/writing/mdc
No issue linked
=> docs(README): fix link to MDC syntax

docs/content/3.guide/2.displaying/2.querying.md
Added example for `_params` api route endpoint.
=> docs(querying): add `_params` to api routes

docs/components/content/Playground.vue, docs/components/content/PropInspector.vue, docs/editor/Editor.vue
Improve playground to accept content from query params.
This will help showcase small syntax features simply by sharing a link.
[Demo](https://deploy-preview-1499--nuxt-content.netlify.app/playground/?content=::prop-inspector{:prop=%27[%221%22,%222%22]%27}%0A::)
=> docs: playground content from query

src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/composables/utils.ts
=> feat(generate): use nitro header instead of header link

docs/content/3.guide/1.writing/7.document-driven.md
Fixed typo in line 114 `Queries are be made` to `Queries are been made`
=> docs(document-driven): fix typo

playground/document-driven/content/_theme.yml, playground/document-driven/layouts/debug.vue, playground/document-driven/nuxt.config.ts, src/runtime/composables/content.ts, src/runtime/pages/document-driven.vue, src/runtime/plugins/documentDriven.ts
=> fix(document-driven): sync page layout

docs/content/4.api/1.components/2.content-list.md
=> docs(content-list):  Updated query reference and added example

src/module.ts, src/runtime/composables/utils.ts
=> fix(navigation): missing composable when navigation is disabled

docs/content/4.api/1.components/5.markdown.md
The ContentSlot links to a broken link.
Just curious to jump in the parent folder (..) to get the correct link.
No issue raised.
Adding a dot to the link to get the correct link.
https://deploy-preview-1588--nuxt-content.netlify.app/api/components/markdown
=> docs: broken link on Markdown API page

docs/content/4.api/2.composables/4.use-document-driven.md
By copying the following code from the documentation
```vue
<script setup lang="ts">
const { page } = useContent()
</script>
<template>
<ContentRenderer :key="page._id" :value="page">
</template>
```
It was giving me an error, it turns out that the ContentRenderer component did not have the closing tag, so I proceeded to update it in the documentation
=> docs(composables): fix close tag ContentRenderer

src/runtime/components/ContentList.vue, test/features/components.ts, test/fixtures/basic/pages/dogs-list.vue
=> fix(`<ContentList>`): respect `query.path` when `path` is missing

src/module.ts, src/runtime/components/ContentDoc.vue
resolves nuxt/content#1583
In SSG on client hydration `useRoute().path` contains additional slash at the end of path which cause cache miss in `asyncData`.
`ContentDoc` is responsible for fetching single content, so we can safely remove this trailing slash.
=> fix(`<ContentDoc>`): render blink in SSG

playground/shared/server/api/parse.ts, src/runtime/server/api/highlight.ts
Use explicit `eventHandler` preparing for rc.12 and h3@0.8x
=> fix: update h3 usage

src/runtime/components/Prose/ProseH1.vue, src/runtime/components/Prose/ProseH2.vue, src/runtime/components/Prose/ProseH3.vue, src/runtime/components/Prose/ProseH4.vue, src/runtime/components/Prose/ProseH5.vue, src/runtime/components/Prose/ProseH6.vue
My new local projects always get the following error in edge channel:
```
500
useRuntimeConfig is not defined
```
<details>
<summary>View full log</summary>
Webpage:
```
500
useRuntimeConfig is not defined
at _sfc_main.setup (./node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.js:39:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7135:29)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7090:11)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:299:22)
at renderComponentSubTree …
```
=> fix(anchorLinks): add useRuntimeConfig imports

playground/basic/content/0.index.md, playground/basic/pages/[...slug].vue, src/runtime/composables/navigation.ts, src/runtime/composables/query.ts
resolves nuxt/content#1607
In SSG deployment, all 404 request are redirected to generated `404.html` and API's with 404 status return invalid response. (They return status code 200 instead of 404)
=> fix: detect 404 api responses in SSG

docs/content/3.guide/1.writing/2.markdown.md
#1610 
I added a section in the documentation to explain how to use local images inside the markdown file.
There's no mention of how to use local images in the documentation. 
It might confuse beginners who wish to use local images in their content.
Resolves #1610
=> docs: guidance on using local images

docs/content/3.guide/1.writing/7.document-driven.md, docs/content/3.guide/3.recipes/1.sitemap.md
correct to use correct apostrophe character --> replace ` and ’ with '
=> docs: fix apostrophe character

docs/content/4.api/1.components/4.content-query.md
Fixed an error in the Where clause for ContentQuery documentation. Before, ContentQuery passed `data` variable to the slot, which was not used and instead `authors` was used in its place. `data` is replaced with `authors` to fix this error.
=> docs: fix error in ContentQuery where clause example

docs/content/4.api/3.configuration.md, docs/nuxt.config.ts
=> docs: update sources

src/runtime/components/ContentList.vue, src/runtime/components/ContentQuery.vue
=> fix(ContentList): handle props change and fix slots default

package.json, src/runtime/query/match/pipeline.ts, src/runtime/server/api/query.ts, src/runtime/server/content-index.ts, src/runtime/server/preview.ts, src/runtime/server/storage.ts, src/runtime/utils/query.ts, yarn.lock
=> refactor: improve typings and simplify logic

docs/content/4.api/1.components/3.content-navigation.md
I didn't see an issue for this, but I can make one if that's preferred.
Updated the HTML in the navbar example from using `div` to using `ul`/`li`. Since many people may copy the example HTML wholesale, using a list inside the nav will start them out with better practices; as per [W3C tutorial](https://www.w3.org/WAI/tutorials/menus/structure/#menu-representation).
=> docs(a11y): Use list for nav example

src/module.ts, src/runtime/composables/client-db.ts, src/runtime/composables/utils.ts, src/runtime/server/api/cache.ts, test/__snapshots__/custom-api-base.test.ts.snap, test/custom-api-base.test.ts, test/features/navigation.ts, test/features/regex.ts
=> feat(module): introduce `api.baseURL` and deprecate `base`

src/runtime/server/api/highlight.ts, test/features/highlighter.ts
=> fix(shiki): issue with merging multiple themes

src/runtime/server/api/query.ts
=> fix(query): invalid response on missing contents

test/__snapshots__/custom-api-base.test.ts.snap, test/custom-api-base.test.ts
=> fix(test): fix typo

src/runtime/markdown-parser/compiler.ts, test/features/parser-markdown.ts
resolves nuxt-themes/docus#678
=> fix(markdown): remove double and trailing dashes from heading ids

src/runtime/components/ContentRenderer.vue, test/basic.test.ts, test/custom-api-base.test.ts, test/fixtures/basic/pages/features/empty-slot.vue
NA
- Simplify conditional checks
- Add an extra test outcome
=> refactor(ContentRenderer): simplify conditions

src/runtime/plugins/documentDriven.ts
=> feat(document-driven): introduce `start` and `finish` hooks

docs/content/3.guide/1.writing/8.vue-component.md, src/module.ts
https://github.com/nuxt/content/issues/1732
Removes the error messages for components
While being a good idea, I think this kind of informations belongs in documentation, not in CLI output.
Feel free to close if you think opposite way, but I kind of agree with #1732
=> chore(logging): cleanup logging

src/module.ts, src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/server/content-index.ts, src/runtime/server/storage.ts, src/runtime/transformers/markdown.ts, test/__snapshots__/basic.test.ts.snap, test/__snapshots__/custom-api-base.test.ts.snap, test/basic.test.ts, test/custom-api-base.test.ts, test/features/content-query.ts, test/features/locales.ts, test/features/renderer-markdown.ts, test/fixtures/basic/content-fa/translated.md, test/fixtures/basic/content/translated.md, test/fixtures/basic/nuxt.config.ts
Contents with same `_path` and different locales should exist in the Index
resolves #1737
=> fix(query): fallback to default locale if query has no filter on `_locale`

src/module.ts, src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/utils/json.ts, src/runtime/utils/query.ts
=> feat(query): fully cacheable api

docs/content/4.api/3.configuration.md
=> docs: update to match v2.3 behaviour

src/module.ts, src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/composables/utils.ts, src/runtime/plugins/documentDriven.ts
=> fix(module): put query parameters removal under an experimental flag

src/module.ts, src/utils.ts
=> fix(build): do not register web-socket plugin on non-dev env

src/runtime/composables/navigation.ts, src/runtime/composables/query.ts, src/runtime/server/storage.ts
resolves #1558
resolves #1399
This PR removes the limitation of `queryContent` and now we are able to use it like:
```vue
<template>
<div>
<ContentNavigation v-slot="{ navigation }" :query="querpath">
<pre>{{ navigation }}</pre>
</ContentNavigation>
</div>
</template>
<script setup>
const querpath = queryContent('blog');
</script>
```
=> fix(query): ensure default values always apply to query params

docs/content/3.guide/2.displaying/1.rendering.md
ContentRenderer `source code` used to deadlink to https://github.com/nuxt/content/blob/main/src/runtime/components/ContentRenderer.ts,
now it links to https://github.com/nuxt/content/blob/main/src/runtime/components/ContentRenderer.vue instead
=> docs: fix ContentRenderer source link

src/runtime/transformers/shiki/highlighter.ts
Previously we were producing code like this:
```html
<span class=\"ct-2c497b\"><</span>
```
which breaks the dom tree - or worse, renders the highlighted code directly as HTML elements.
Looking through the codebase it seems likely that this fix might need to be applied elsewhere too and it would be worth a quick look.
=> fix: sanitize highlighted text

src/runtime/transformers/shiki/shiki.ts, test/features/highlighter.ts
Highlight the excerpt.
Because the excerpt contains a code too.
=> feat(shiki): highlight excerpt

docs/content/4.api/1.components/7.prose.md, src/runtime/components/Prose/ProseCode.vue, src/runtime/markdown-parser/handler/code.ts, test/features/parser-markdown.ts
Don't drop a info from fenced code
````markdown
```javascript[file.js]{4-6,7} meta-info=val
export default () => {
console.log('Code block')
}
```
````
So `meta-info=val` will be accessible from the document tree after parsing. Property `meta` will be next to `language`, `filename`, `highlights`.
It can help to do other modifications with remark plugins, transformers, or ProseCode component.
=> feat(markdown): keep meta from fenced code block

docs/content/3.guide/1.writing/2.markdown.md, src/runtime/markdown-parser/index.ts, test/features/parser-markdown-excerpt.ts
If there is no `` divider in the text then the excerpt is a copy of full content.
This change adds new boolean variable `excerptIsBody` into the document next to `excerpt`.
- It can help to improve performance and don't process the excerpt (just make a copy of body).
- It can help to don't show link to full text if there is nothing to read more.
=> feat(markdown): don't create excerpt if there is no <!--more-->

src/runtime/components/Prose/ProseA.vue
it simply add target to NuxtLink.
=> Replacing blank with target in ProseA

src/module.ts
reported in https://github.com/Atinux/nuxt-typo-readme/pull/4
=> fix(highlighter): define missing env in Vite

src/runtime/transformers/shiki/highlighter.ts, src/runtime/transformers/shiki/languages/mdc.tmLanguage.ts
https://github.com/nuxt/content/issues/1823
See linked issue
=> fix: JSON import type assertion

src/runtime/components/ContentRendererMarkdown.vue, test/features/renderer-markdown.ts, test/fixtures/basic/content/_partial/xss.md
=> fix(markdown): XSS Prevention

src/runtime/utils/json.ts, src/runtime/utils/query.ts, test/basic.test.ts, test/features/content-query.ts
=> fix(query): decode unicode params

src/runtime/components/Prose/ProseH1.vue, src/runtime/components/Prose/ProseH2.vue, src/runtime/components/Prose/ProseH3.vue, src/runtime/components/Prose/ProseH4.vue, src/runtime/components/Prose/ProseH5.vue, src/runtime/components/Prose/ProseH6.vue
#1864
Adding checks if anchor-id is present in headings, if `id` is not defined, the link isn't generated
=> fix(headings): don't generate link if `id` is missing

src/runtime/transformers/shiki/highlighter.ts
#1883
Using `div`s for highlighted code blocks (instead of `span`s) to preserve line breaks when copying selection in **Firefox**.
`Inline code`s aren't affected, because those only use the children of the first "line" as content.
=> fix(code block): use <div> for Firefox code block line breaks

docs/content/4.api/1.components/2.content-list.md
No issue found, do I need to create one for this little change?
This PR simply updates/fixes the query example: The `sort` parameter must be an array hence the type: `SortOptions[]`
=> docs: update content list query example

src/module.ts, src/runtime/components/ContentRendererMarkdown.vue, src/runtime/transformers/component-resolver.ts
Introducing new transformer for client side usage to pre import dynamic components that used in markdown during parse.
Background:
Using dynamic component in Markdown, causes a blink in client side rendering. This behavior exists because `Suspense` shows an empty fallback while `MarkdownRendere` tries to load dynamic components. With preloading components in parse time, we can avoid this blink and layout should and force Suspense to not show the fallback state.
Additionally, with this feature, we will be able to load non-global component.
=> feat: introduce `component-resolver` transformer

.npmrc, docs/.npmrc, docs/components/content/Playground.vue, docs/package.json, docs/pnpm-lock.yaml, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> docs: fix deployment

src/runtime/composables/client-db.ts
=> feat(client-db): allow possibility to ignore some sources from client storage

docs/content/3.guide/1.writing/3.mdc.md
https://github.com/nuxt/content/issues/1494, https://github.com/nuxt/content/issues/1573, https://github.com/nuxt/content/discussions/1492
This PR adds examples for arrays and objects that can be passed to props as JSON string with the inline method. Additionally I added a small section with an explanation that multiple props can be passed with a space as a separator as there has been some confusion about this in multiple issues and discussions.
This was not yet documented and only mentioned by @farnabaz in the linked issue.
Also see this discussion about a similar problem: https://github.com/nuxt/content/discussions/1881
=> docs: add examples for JSON string for inline props

src/module.ts
fix #1869
Here the situation:
- You start your nuxt dev server
- `.nuxt` is generated with a `content-cache` folder and a `content-index.json`
- You stop your nuxt dev server
- You add files in content or you modifie the architecture
- You restart your nuxt dev server but because your `content-index.json` is already there, index is not refreshed (https://github.com/nuxt/content/blob/main/src/runtime/server/content-index.ts#L9)
This situation also occure when you pull from remote with new files in the content folder with a stopped dev server.
Here, I remove the `content-index.json` file every time nitro restart to be sure that a fresh index is generated before the user restart to code.
I was thinking about using a hash but I didn't find good data to hash and this could require to check …
=> fix: refresh content-index on nitro start

src/runtime/query/match/pipeline.ts, test/features/query/query.test.ts
=> fix(findSurround): allow before and after to be 0

src/runtime/composables/helpers.ts, src/runtime/composables/utils.ts
=> fix(document-driven): page layout detection

src/runtime/types.d.ts
=> fix(type): content locale

src/runtime/composables/head.ts
Resolves #1980 
Replaced `name` attribute by `property` for og meta tags
Resolves #1980
=> fix: set property instead of name for og metadata

src/runtime/composables/utils.ts
We recently deprecated a Nuxt 2 compatibility feature (https://github.com/nuxt/nuxt/pull/20082) and it seems that `@nuxt/content` was still using this feature.
(We plan to remove it entirely by v3.5.)
=> fix: access `experimental` config from `public` key

src/runtime/components/ContentRendererMarkdown.vue
=> fix(ContentRendererMarkdown): prevent `undefined` error on component resolve

package.json, playground/shared/nuxt.config.ts, pnpm-lock.yaml, src/module.ts, src/runtime/components/ContentRendererMarkdown.vue, src/runtime/composables/client-db.ts, src/runtime/composables/navigation.ts, src/runtime/composables/preview.ts, src/runtime/composables/query.ts, src/runtime/composables/utils.ts, src/runtime/server/navigation.ts
- Safari blocks storing/accessing cookies inside iframe. ([see](https://webkit.org/blog/8124/introducing-storage-access-api/)) With this PR, module supports session storage as secondary storage to look for preview token.
- `<ContentRendererMarkdown>` adds `data-content-id` attribute to its root element
=> fix(preview): use `sessionStorage` to keep token

src/runtime/plugins/documentDriven.ts
=> fix(document-driven): ensure layout is set on hydration

docs/content/4.api/2.composables/1.query-content.md
Suggesting an example to add to demonstrate how to use the additional sorting options for queryContent(). The previous wording was not clear
=> docs: add example of additional sorting options for queryContent

src/runtime/markdown-parser/handler/link.ts, test/features/parser-markdown.ts
Does not know if it's a bug fix or an enhancement.
The PR consists of allowing hash in a relative title.
Example of an URL used in our md files : 
`../docs/04.developer-guide/04.inputs.md#set-inputs-with-curl`
Without the hash part, this works fine and the URL is well interpreted, but we notice that having a hash will break the functionality.
In fact, the method `normalizeLink()` works only with relative files that end with `.md`, so we added hash handling in this function, which is just a regex that removes hash, and set it back before returning.
=> fix(link): Remove hash before checking if ending by '.md'

src/module.ts
https://github.com/nuxt-modules/tailwindcss/issues/671
Prepares for incoming change to Tailwind module.
=> fix(tailwind-integration): allow content as object

playground/shared/nuxt.config.ts, src/runtime/transformers/shiki/highlighter.ts, src/runtime/transformers/shiki/shiki.ts, src/runtime/transformers/shiki/types.d.ts, test/features/highlighter.ts
https://github.com/nuxt/content/issues/2069
Resolves #2069
Before: 
After: 
If you have any questions or need to modify please do not hesitate to :)
=> feat(shiki): Support italic, bold and underline styles

docs/content/3.guide/2.displaying/1.rendering.md
`<ContentDoc />` will perform head management regardless of whether the path parameter is passed in, unless the `head` prop is specified as `false`.
Update old documents according to the correct behaviour.
=> docs: remove outdated description

docs/content/3.guide/1.writing/7.document-driven.md
Update document-driven page in documentation to reorder description to their respective page slots components (specifically `<DocumentDrivenNotFound />`: "This component will be shown when no page has been found for the current URL.").
=> docs: reorder document-driven page slots components description

src/runtime/server/storage.ts
resolves #2000 
Replaces CRLF (or CR) line endings with LF to prevent a `vue` hydration mismatch
`\r\n || \r => \n`
=> fix: replace crlf line endings with lf

src/utils.ts
=> fix: use `consola.withTag` instead of `kit.useLogger`

docs/content/4.api/3.configuration.md, src/module.ts, src/runtime/server/storage.ts, src/runtime/transformers/path-meta.ts
close #2162 
Currently, if we construct a path like /zh-CN/foo.md, the corresponding document cannot be found. This is because the path is automatically converted to lowercase. I think the existence of such a path is reasonable and should not be converted. I don't understand why this is done, so in order not to introduce destructive changes, I added a flag named keepUppercase to allow uppercase letters in the path.
I wasn't sure where this flag should be placed, so I tentatively put it under the experimental options.
Resolves #2162
=> fix: uppercase in path

docs/content/4.api/1.components/4.content-query.md
fix #2173
Without `find="one"`, the query return an array. So the condition, https://github.com/nuxt/content/blob/main/src/runtime/components/ContentRenderer.vue#L73, can not be true in the `ContentRenderer` component. I update the example to easily copy-paste code.
=> docs: update slots example for the content-query component

docs/content/2.get-started.md, docs/content/3.guide/2.displaying/1.rendering.md, docs/content/4.api/1.components/1.content-doc.md, docs/content/4.api/1.components/2.content-renderer.md, docs/content/4.api/1.components/4.content-query.md, docs/content/4.api/1.components/7.prose.md, docs/content/4.api/2.composables/4.use-document-driven.md, docs/content/6.blog/1.announcing-v2.md, playground/basic/components/content/ProseCode.vue, playground/basic/content/1.real-content/content.md, playground/basic/content/2.features/3.mdc-highlighter.md, playground/basic/content/2.features/8.custom-prose.md, src/runtime/markdown-parser/handler/utils.ts, test/features/parser-markdown.ts
fix #2166 
For a code block, if filename was `[...page].vue`, regex was stoping at `[...page`. This PR fix it.
=> fix: allow ] in filename code block

docs/components/content/V1DocsLinks.vue
- wrapping v1 link buttons on small screens to prevent overflow
- removing class `ml-2` as it is unused
- adding a link button to the Russian docs page
=> docs(v1): link button wrapping for small screens

docs/content/3.guide/1.writing/3.mdc.md
As Tailwind isn't used by Docus anymore, the class names aren't providing styling by themselves. I added the corresponding style tags to fix this.
This has also been [changed for lines 347-349](https://github.com/nuxt/content/commit/1823c0defcc836ebfdfc0f1bf9be1e8ac19f0cc7#diff-486c5f2e2433a70cd8bace1d6253fd758d7ef340bb21fa57dcf135ec9eca2801R347-R349) in a previous PR #1982.
I am not sure, if it is good to do this, because the class name styling won't work if someone tries doing it with Docus.
Maybe a warning or info should be added, that the styling with classes just works with e.g. Tailwind?
I mean... the props are assigned, just the styling would be missing.
=> docs(mdc): fix {attribute} examples

src/runtime/components/Prose/ProseImg.vue
=> fix(ProseImg): prevent conflict between `src` and baseURL

docs/content/2.get-started.md
None
When I try Content for the first time, I already instantiate a nuxt app with the default template.
My `app.vue` was looking like that : 
```html
<template>
<div>
<NuxtWelcome />
</div>
</template>
```
After executing what was written in the getting started, my nuxt app wasn't displaying my `content/index.md` page.
Instead, I was still seeing the `<NuxtWelcome />` component.
I'm not sure it's useful to create an issue for this, so I create a PR directly.
=> docs: add warning for NuxtPage in app.vue (2.get-started.md)

src/runtime/components/ContentRenderer.vue, src/runtime/query/query.ts, test/basic.test.ts, test/fixtures/basic/content/excerpt.md, test/fixtures/basic/pages/excerpt-only.vue
=> fix(ContentRenderer): render contents only with excerpt

src/runtime/components/ContentList.vue
The slot property is `list` and not `data`, so the current type is inaccurate and fails typechecking when used as:
```vue
<ContentList v-slot="{ list }">...</ContentList>
```
=> fix(ContentList): component slot typechecking

src/module.ts
=> fix(module): remove deprecated `resolveModule`

package.json, playground/basic/content/0.index.md, playground/basic/nuxt.config.ts, pnpm-lock.yaml, src/module.ts
=> fix(tailwindcss): Tailwindcss HMR support for content files

src/runtime/server/storage.ts
=> fix(storage): prevent duplicate parsing

docs/pages/index.vue
The [new docs](https://content.nuxt.com) (#2310) have a gradient on the home page which is `positioned absolute` and overflows to the right of the page, as it takes 100% width.
(Checked with `Firefox 117.0.1` and `Chromium 116.0.5845.187` on Linux)
Possible changes are
- setting the parent element to `hide overflow(-x)`
-> gradient shifted slightly right
- or to add a `left: 0` to the absolutely positioned element
-> gradient centered
---
I decided to use `left: 0` which looks like this:
=> docs: fix page overflow

src/runtime/components/ContentRendererMarkdown.vue
External variables binding for https://github.com/nuxt/content/issues/2053
I've implemented a feature that allows for external variable binding within the Nuxt Content. This enhancement enables seamless integration of external variables into the project, thereby enhancing its functionality and flexibility. 
I remain enthusiastic about contributing to the Nuxt Content project and ensuring its continued growth and improvement.
```
<template>
<div>
<ContentRendererMarkdown :value="data" :data="mdcVars"/>
<button type="button" v-on:click="mdcVars.name = 'Hugo'">Change name</button>
</div>
</template>
<script setup lang="ts">
const { data } = await useAsyncData(() => queryContent('test').findOne());
const mdcVars = ref({ name: 'Maxime'});
</script>
```
**test.md**
``` 
```
=> feat: add binding for external data

src/runtime/query/match/pipeline.ts
Since #2213 (?), our build generates a lot of the following error. After digging in the nuxt content code, it seems that one of our `queryContent` call is generating a regex in `$where`, which leads to that crash.
```
ERROR  [nuxt] [request error] [unhandled] [500] input.endsWith is not a function                                                                                        3:49:03 PM
at withTrailingSlash (./node_modules/.pnpm/ufo@1.3.1/node_modules/ufo/dist/index.mjs:327:18)
at joinURL (./node_modules/.pnpm/ufo@1.3.1/node_modules/ufo/dist/index.mjs:389:13)
at ./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:17008:60
at Array.find (<anonymous>)
at fetchDirConfig (./.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:17008:30)
at …
```
=> fix: ignore regexes in fetchDirConfig

docs/content/2.usage/2.markdown.md
=> docs: update bindings with default value

docs/content/6.recipes/3.sitemap.md
I believe this guide was made when there was no sitemap solution for Nuxt 3, now that there is and it integrates with Nuxt Content, I think it should be linked.
=> doc: link Nuxt Simple Sitemap for full featured sitemaps

docs/content/3.composables/7.search-content.md
_payload.josn should be _payload.json
Fixed a typo in 7.search-content.md, _payload.josn should be _payload.json
=> fix(docs): 7.search-content.md typo

docs/content/4.components/2.content-renderer.md
Updated the docs for ContentRenderer as it was misleading. When using custom components in a MD file, user should pass a map which should be 
```
const components = {
'custom-component': CustomComponentObject,
}
```
Hope that help
=> docs: update ContentRenderer custom components

src/module.ts, src/runtime/server/api/cache.ts
fix #2415
Enable the `/api/cache.json` endpoint only for the clientDb feature. Otherwise, it's unnecessary and can be a real pain (build perf and deployment) for huge website.
=> fix: enable cache only for clientDb

build.config.ts, package.json, src/runtime/types/api.ts, src/runtime/types/index.ts, src/runtime/types/query.ts
resolves https://github.com/nuxt/content/issues/2469
This adds support for Bundler TypeScript module resolution. It changes extensions of runtime dir files to `.js` which should be safe as this is a `type: module` project.
I also add a subpath for `@nuxt/content/dist/runtime/types` as this is already documented. But we could also have a more ergonomic subpath for type augmentation.
=> fix: ensure `bundler` module resolution works with runtime type imports

src/runtime/composables/client-db.ts, src/runtime/legacy/composables/client-db.ts, src/utils.ts
Spotted that we can remove these ts-ignores.
=> chore: remove `ts-ignore` as unstorage has fixed subpath export

.nuxtrc, src/module.ts, src/runtime/composables/client-db.ts, src/runtime/legacy/composables/client-db.ts, src/runtime/server/api/search.ts, src/runtime/server/navigation.ts, src/runtime/server/storage.ts, src/runtime/types/query.ts, tsconfig.json
This is a 'canary' pull request. It aims to ensure that the ecosystem is ready for a shift in the default Nuxt TypeScript module resolution from 'Legacy' to 'Bundler': https://github.com/nuxt/nuxt/pull/24837. You'll need to run your build + type checking tests to verify that things still work; I'm hoping that CI will do that for us so we get an immediate indication of whether there's anything to investigate further here.
'Bundler' module resolution is [recommended by Vue](https://github.com/vuejs/tsconfig/blob/mainz/tsconfig.json#L24-L26) and [by Vite](https://vitejs.dev/guide/performance.html#reduce-resolve-operations), but unfortunately there are still many packages that do not have the correct entries in their `package.json`.
This might include this module or packages that are _used_ …
=> chore: test bundler module resolution

docs/content/2.usage/3.search.md
Fix an incorrect variable name in the template example.
=> fix: search result variable name

src/module.ts, src/runtime/composables/search.ts
The default value has been assigned here: https://github.com/nuxt/content/blob/12d26702940c80f4f57bb733984b8f3e24e7c46f/src/module.ts#L528-L550
=> fix(types): fields in `experimental.search` can be optional

src/module.ts
discovered in https://github.com/nuxt/nuxt/actions/runs/7472932540?pr=25109
It looks like `options.getComponents` doesn't accept an argument (L608). This removes the unused argument...
=> chore: remove unused argument

docs/content/3.composables/7.search-content.md
mention that `searchContent` is an experimental feature
=> docs: mention that `searchContent` is an experimental feature

src/module.ts
=> fix(ContentSlot): detect multiline usage

build.config.ts, package.json
resolves https://github.com/nuxt/content/issues/2512
We probably need to fix this in nuxt/module-builder, but adding the new entrypoint didn't overwrite existing one, so both `.js` and `.mjs` files were being created.
=> build: do not emit `.mjs` in runtime directory

docs/content/1.get-started/2.configuration.md, docs/content/2.usage/2.markdown.md, docs/content/4.components/7.prose.md
According to https://github.com/nuxt/content/blob/main/src/module.ts#L343
We replace `ProseCode.vue` define into `ProseCodeInline.vue`
And using `ProsePre.vue` to wrap `ProseCode.vue`
So, if i want to use custom prose component, I have to named `ProsePre.vue` in order to replace the code block in `.md`
=> docs: fix incorrect naming & link path in Component/Prose 

src/runtime/server/storage.ts
resolves #2449
The bottleneck in the pre-rendering phase is getting contents list from file system. By caching the list in the pre-render process, the generation time will drop significantly.
This change reduce the generation time in Content docs from 15s to 5s on my machine
=> perf(content-list): cache contents list during generation and per-request

README.md, docs/content/1.get-started/2.configuration.md, docs/content/2.usage/2.markdown.md, package.json, playground/basic/content/2.features/3.mdc-highlighter.md, playground/basic/nuxt.config.ts, playground/shared/nuxt.config.ts, pnpm-lock.yaml, src/module.ts, src/runtime/transformers/markdown.ts
This PR updates options from the new mdc module to forward them.
Also move Shikiji to Shiki
=> feat: adopt to mdc v0.4

docs/content/1.get-started/2.configuration.md
Correct prop is "showURL" according to the listhen package : https://www.npmjs.com/package/listhen
=> typo in showURL prop

docs/content/3.composables/1.query-content.md, src/runtime/query/match/index.ts, src/runtime/types/index.ts, src/runtime/types/query.ts
Most of the match operators were undocumented. I added the descriptions of the comments in https://github.com/nuxt/content/blob/main/src/runtime/query/match/index.ts
=> docs: add descriptions of all match operators

src/module.ts
N/A
The current JSDoc comment mentions that the default setting for highlight.langs is `['js', 'ts', 'vue', 'css', 'html', 'vue', 'shell']`. However, the actual default in @nuxtjs/mdc is `['js', 'jsx', 'json', 'ts', 'tsx', 'vue', 'css', 'html', 'vue', 'bash', 'md', 'mdc', 'yaml']`.
=> docs: correct default `highlight.langs` in JSDoc

src/runtime/types/query.ts
#2545 
Resolves #2545 
This PR enables having better types when using the .only() function and uses the const type parameter feature that was introduced in Typescript 5.0
=> fix(types): use const type parameter for QueryBuilder.only

src/runtime/server/content-index.ts
Resolves https://github.com/nuxt/content/issues/2354
Split `getContent` promises to chunks, to prevent EMFILE error.
=> fix: split `getContent` to chunks in `getIndexedContentsList` (#2354)

src/runtime/types/index.ts, src/runtime/types/query.ts
#2546 
> This PR enables having better types when using the .only() function and uses the const type parameter feature that was introduced in Typescript 5.0  
I noticed that my previous PR only included the .only() in runtime/types/query.ts when it should have also included the ones in runtime/types/index.ts
=> fix(types): add const type parameter for .only() and .without()

src/module.ts
resolves https://github.com/nuxt/content/issues/2381 together with https://github.com/nuxt-modules/mdc/pull/160
Vite requires dependencies that are optimised to be installed, but `slugify` won't be directly installed by users. So we can indicate to vite to resolve the dependency from within another dependency that _is_ installed, in this case `@nuxt/content`...
We also have to modify the list for deps injected by `@nuxtjs/mdc` as that module won't be directly installed _either_.
=> fix: optimise nested dependencies

docs/pages/index.vue
similar to [devtools/#620](https://github.com/nuxt/devtools/pull/620)
=> docs: update ui-pro ui props

src/runtime/composables/head.ts, src/runtime/composables/navigation.ts, src/runtime/composables/preview.ts, src/runtime/composables/query.ts, src/runtime/composables/utils.ts, src/runtime/legacy/composables/navigation.ts, src/runtime/legacy/composables/query.ts, src/runtime/legacy/plugins/documentDriven.ts, src/runtime/pages/document-driven.vue, src/runtime/plugins/documentDriven.ts, src/runtime/plugins/ws.ts, src/runtime/transformers/component-resolver.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …
=> fix: opt in to `import.meta.*` properties

docs/content/1.get-started/1.installation.md, docs/content/7.v1/1.getting-started/2.installation.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
=> docs: use new `nuxi module add` command in installation

src/module.ts
resolves https://github.com/nuxt/content/issues/2610
=> fix(module): convert `content-slot` to `MDCSlot`

src/module.ts
There was a missing space between two strings joined using the join() method within the logger.warn() function call.
=> chore: add missing space between two strings joined in logger.warn().

src/runtime/server/search.ts
This PR fixed custom search's issue with page's first paragraphs.
=> fix(search): keep page's beginning paragraphs

src/module.ts
#2177 
Resolves #2177  by augmenting the NitroRuntimeHook typing to provide typings of hook `content:beforeParse` and `content:afterParse` (and also IDE intellisense of course)
=> fix: add Nitro hooks types declarations

src/runtime/server/storage.ts
=> fix: filter draft files in production

src/runtime/server/api/cache.ts, src/runtime/server/api/navigation.ts, src/runtime/server/content-index.ts, src/runtime/server/storage.ts
This resolves an issue when using nitro-nightly and pre-rendering the pages:
It also avoid creating the storage when not used for better performance 🚀
=> fix: init storage only when used

src/module.ts
=> fix(prerender): ensure `/` exists inside prerender rotues

src/module.ts
Reported in https://github.com/nuxt/content/pull/2673#issuecomment-2185008228
Do not manipulate pre-render routes in module and let Nuxt handle missing `/` in pre-render routes
=> fix(module): do not force prerender index page

docs/content/2.usage/3.search.md
One of the code examples in the [search usage  documentation](https://content.nuxt.com/usage/search) was rendering a promise in html instead of the actual result.
=> fix: add missing `await` keyword in search documentation

docs/content/3.composables/7.search-content.md
This is almost identical to PR #2687
Adds a missing `await` in a searchContent example.
=> docs: Add missing `await` for searchContent docs

docs/content/7.v1/1.getting-started/4.fetching.md, src/types/query.ts, test/features/query/match.test.ts
https://github.com/nuxt/content/issues/437
The `$gte`, `$gt`, `$lt`, `$lte` operators are defined in the Typescript as only taking a number. This is in fact incorrect as they map to the standard JavaScript `>=`, `>`, `<`, `<=` operators which can handle any more types and as the test coverage shows they work perfect with strings.
This fix is needed as anyone trying to use these operators with a string - such as in a common case as filtering by alpha ranges or even a sort-formatted date string - will receive Typescript errors leading them to think this is not the way to do it.
This adds the `string` type to those operators, adds test coverage to prove they work and importantly adds an example to the filtering docs showing how to use the string filtering to sort by a date which is a common …
=> fix: add string type to gt/lt/gte/lte type definitions

docs/content/4.components/6.content-slot.md
As far as I can tell custom ContentSlot components need to be in the `components/content` directory. I spent a whole day trying to figure out how to get these working, then simply moved the components to the content directory and it worked. I double checked this functionality with the stackblitz environment linked below. I tried to find the reference code that would actually enforce this, but I couldn't find it.
https://stackblitz.com/edit/github-syrfpd-jmspgd?file=README.md
=> fix(docs): Update ContentSlot Documentation

docs/content/2.usage/5.typescript.md
#2349
Resolves #2349
Currently, to import the type, you need to specify '@nuxt/content', but the documentation states it should be '@nuxt/content/dist/runtime/types'.
=> docs: fix incorrect TS types import path in documentation

docs/content/1.get-started/1.installation.md
Add warning about using Nuxt Content with SPA static generation (`ssr: false` in Nuxt Config) on the Installation guide in the documentation.
[Issue #1229](https://github.com/nuxt/content/issues/1229)
Documentation edit
The following change to the Installation page of the docs makes a note that Nuxt Content currently requires `ssr: true` to be set due to static SPA (`ssr: false`) being incompatible.
=> fix(docs): add warning about using `ssr: false` with Content

docs/content/2.usage/5.typescript.md
When importing types like that:
`import type { QueryBuilderParams } from '@nuxt/content/dist/runtime/types'`
- typescript gives an error: Cannot find module '@nuxt/content/dist/runtime/types' or its corresponding type declarations Making path: @nuxt/content fixes this error.
=> Update 5.typescript.md - changed types path

src/runtime/server/api/navigation.ts
=> fix: navigation dir confs handle missing query params

src/runtime/transformers/path-meta.ts
- [issue in comment](https://github.com/nuxt/content/issues/1523#issuecomment-2262325189)
- [issue in comment](https://github.com/nuxt/content/pull/2648#issuecomment-2223573143)
Fix [issue in comment](https://github.com/nuxt/content/issues/1523#issuecomment-2262325189) and [issue in comment](https://github.com/nuxt/content/pull/2648#issuecomment-2223573143) that `draft` key not work as expected as [document](https://content.nuxt.com/usage/markdown#front-matter) saying.
>
=> fix: respect `draft` key as `_draft`

docs/content/1.getting-started/5.migration.md, docs/content/3.api/1.query-collection.md, docs/content/3.api/2.query-collection-navigation.md, docs/content/3.api/3.query-collection-item-surroundings.md, docs/content/3.api/4.query-collection-search-sections.md, docs/content/4.components/0.content-renderer.md
This PR fixes a typo in the documentation, changing `useAysncData` to `useAsyncData`. This correction enhances clarity and ensures accuracy in the guidance provided to users.
=> fix: correct typo in documentation from useAysncData to useAsyncData

src/utils/config.ts
Use c12 to load config - it would give lot of other benefits. Let me know if using custom loader was intentional! 🙂
=> chore(config): use c12

src/runtime/composables/query.ts, src/runtime/legacy/composables/query.ts
#2845 
- [ x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Resolves #2845 by applying `encodeURIComponent()` to query param.
I assume that this is not a breaking change?
- [ x ] I have linked an issue or discussion.
- [ nA ] I have updated the documentation accordingly.
=> fix: query url encoding

docs/content/docs/3.utils/1.query-collection.md
=> docs: fix typos in queryCollection page

docs/content/docs/3.utils/1.query-collection.md
A small typo on the `queryCollection` section.
This will probably get copy / paste a lot.
Love the new @nuxt/content package so far.
I didn't find another issue for this typo. Also couldn't find any other typos.
=> docs: fixed the smallest typo ever

docs/content/docs/1.getting-started/4.migration.md
#2885 
The handling of ProseCode, ProsePre, and ProseCodeInline have been updated in Nuxt Content v3. I didn't see instructions for this breaking change when I began my migration and opened a bug (it was not a bug, just a breaking change that hadn't been captured yet)
Resolves #2885
=> docs(migration): added migration instructions for ProsePre, ProseCode, and ProseCodeInline

docs/content.config.ts, docs/content/docs/1.getting-started/2.installation.md, docs/content/index.md, examples/basic/content.config.ts, playground/content.config.ts, src/utils/config.ts, src/utils/index.ts
This is NOT a breaking change.
Devs can still use `export const collection` (as `c12` will fallback non-default export). However, in consistency with other `.config` files that tend to use default export and providing type-safety, having `defineContentConfig` would be nice.
=> feat(config): provide defineContentConfig utility

docs/content/docs/1.getting-started/3.configuration.md, src/module.ts, src/types/module.ts, src/types/path-meta.ts, src/utils/content/index.ts, src/utils/content/transformers/path-meta.ts, test/unit/parseContent.path-meta.test.ts
resolves #2889
Allow modifying [`slugify`](https://github.com/simov/slugify) options to improve locale support.
```ts [nuxt.config.ts]
export default defineNuxtConfig({
content: {
build: {
pathMeta: {
slugifyOptions: {
// Keep everything except invalid chars, this will preserve Chinese characters 
remove: /[$*+~()'"!\-=#?:@]/g,
}
}
}
}
})
```
=> feat(build): allow modifying `slugify` options

src/runtime/api/query.post.ts, src/utils/schema.ts
https://github.com/colinhacks/zod/issues/2596#issuecomment-1643053289
The `import { z }` syntax from Zod has issues with tree shaking, bloating the bundle size more than necessary. By switching to a namespace import the tree shaking can act more effectively
=> perf: reduce zod bundle size

docs/content/index.md
Admittedly I neglected to open a tracking issue for this. It's a very miniscule PR.
I noticed a few of the cards on the home page (https://content3.nuxt.org) were a bit out of order. It was really triggering my OCD, so I decided to switch 'em around real quick so all of the card bodies are matching the correct titles. It's less confusing for new users :)
If you're a visual person, like I am, this image pretty much sums up the changes I've made:
=> fix(docs): ensure card prose on the homepage matches the correct title

src/module.ts, src/runtime/internal/studio/collection.ts, src/utils/collection.ts, src/utils/dev.ts, test/unit/generateCollectionInsert.test.ts
There is some situations that parsed content length might exceed 100K characters (specially for the files with multiple codeblock).
This PR breaks those insert queries into two queries one insert and one update
=> fix(module): split big sql queries into two

docs/content/docs/7.advanced/5.hooks.md, src/types/module.ts, src/utils/collection.ts, src/utils/content/index.ts, test/unit/hooks.test.ts
https://github.com/nuxt/content/issues/2921
The runtime hooks from Content v2 were useful for modules to provide an integration with markdown files. For example, allowing users to provide custom frontmater keys or inferring data from the markdown body.
- [Nuxt Sitemap - Nuxt Content Integration](https://github.com/nuxt-modules/sitemap/blob/main/src/runtime/server/plugins/nuxt-content.ts)
In Content v3 these runtime hooks are moved to the build time which is a great performance win, however, we no longer have access to the parsing hooks. 
This PR introduces the `collection:parsedFile` hook to allow modules to start integrating with v3.
=> feat: pre / post parsing hooks

src/module.ts, src/utils/config.ts, test/base.test.ts
Another small PR inspired from my reading of the implementation for v3..
A few bits I had noticed:
After #2829, we would have enabled `.config/` directory (or even config in different extensions) - but I realised that the fsStat before loading the config would not allow us for this. So it started with that, then I went ahead to parallelise the call to `loadContentConfig`, and then resolve `collectionMap`. I realised that calling `resolveCollections` and iterating over collections was not necessary (as the key is the `collection.name`), so instead we use a reducer to override any low-level layer collections (ideally we would have wanted to use `defu`, but that is deep-default and may have side-effects for collection schemas). In addition to that, I also ensured that the configurations …
=> feat(config): enable watch for all layer configs and load in parallel

docs/content/docs/1.getting-started/4.migration.md
In v2, this was done automatically. It has to be explicitly added in v3.
The issue raised can be found here #2930 
While migrating from v2, I noticed that all the components that were once global and could be passed as a string to the `<component />` element were no longer being displayed. The components created under `components/content` were no longer automatically registered as global components.
This PR just adds this note to the migration page so that users know that they have to explicitly mark components within the `components/content` folder as global.
=> docs(migration): state how to register components in `content` folder as global components

docs/content/docs/5.components/1.slot.md
No relevant issue was found. 
The v3 documentation for named slots wrongly stated that you should use the 'use' prop instead of the 'name' prop to create a named slot. Fixed text mistake: 'use' --> 'name'.
The correctness of the documentation. 
I didn't find an open issue for that. It's my first contribution here. Sorry for not knowing if I should create an issue first or simply the PR itself to fix it is enough. Please let me know.
=> docs: fixed names slots prop name

src/runtime/internal/navigation.ts, test/unit/generateNavigationTree.test.ts
resolves #2958 
Index files should be merged with duplicate siblings
=> fix(navigation): prevent duplicate nodes

src/runtime/internal/navigation.ts, src/runtime/internal/query.ts, src/runtime/nitro.ts, test/unit/generateItemSurround.test.ts, test/unit/generateNavigationTree.test.ts
=> fix(navigation): respect user defined order

docs/content/docs/4.utils/3.query-collection-item-surroundings.md
docs: fix example code by removing underscores from paths
- [ x] 📖 Documentation (updates to the documentation or readme)
Updated the example to replace `_path` with `path` to match the updated data structure. This ensures the documentation is accurate and reflects the correct usage of path properties in templates.
=> docs: invalid path filed in query-collection-item-surroundings docs

docs/app/components/post/PostPage.vue
@farnabaz There is still an issue with the surround links being in the wrong order at the bottom.
=> docs(PostPage): fix surround order

docs/content/docs/4.utils/1.query-collection.md
NA
Update the docs to indicate that the `IN` operator should be in caps. The related typescript definition:
```typescript
export type SQLOperator = '=' | '>' | '<' | '<>' | 'IN' | 'BETWEEN' | 'NOT BETWEEN' | 'IS NULL' | 'IS NOT NULL' | 'LIKE' | 'NOT LIKE'
```
=> docs: Update IN filter operator in docs

docs/content/docs/4.utils/2.query-collection-navigation.md, docs/content/docs/4.utils/3.query-collection-item-surroundings.md, src/runtime/internal/query.ts, test/unit/collectionQueryBuilder.test.ts
https://github.com/nuxt/content/issues/2927
After some investigation, I discovered that #2927 is caused by the following code in `query.ts`, where the `value` is wrapped in quotes. This prevents boolean results from being found. 
https://github.com/nuxt/content/blob/d5efff1fdd03612d712661bae7f4596965082e44/src/runtime/internal/query.ts#L52
In SQLite, boolean values are stored as `0` and `1`. When searching with `true` or `false`, they are converted to `0` and `1`, which works fine. However, when searching with `'true'` or `'false'`, it fails.
The solution is to convert them to `0` and `1` before adding quotes.
This should work with both `0/1` and `true/false` in query condition.
Resolves #2927
=> fix: convert boolean value to number in query condition

src/runtime/internal/database.client.ts
resolves #2993
dropping loggers causes undefined exceptions in the client due to existed logger in sqlite WASM. Overriding the logger prevents undefined errors.
=> fix(wasm): override logger functions

src/runtime/api/query.post.ts, src/runtime/internal/security.ts, test/unit/assertSafeQuery.test.ts
=> fix: validate query before execute

src/runtime/app.ts, src/runtime/nitro.ts
=> feat(search): allow filtering contents in search sections

docs/content/docs/1.getting-started/3.configuration.md
Updated the docs using a more recent object property name. As per Nuxt content v3.1.0, the property `binding` is deprecated in favor of `bindingName`, as configured in the type [`D1DatabaseConfig`](https://github.com/nuxt/content/blob/bfc58ccf2a155b48d8f585ea8bf206f93c801c27/src/types/module.ts#L8).
=> fix(docs): Use `bindingName` instead of `binding`

src/runtime/app.ts
fix #3120
This resolves the broken type definition for `queryCollectionItemSurroundings` in the built module. I am unsure why `nuxi` is building a broken TS file but adding an explicit import and then export (to stop it being tree-shaken) seems to fix this issue with the `ContentNavigationItem` being incorrectly bundled.
=> fix: `queryCollectionItemSurroundings` type definition in built module

src/module.ts, src/runtime/internal/database.server.ts, src/utils/collection.ts, test/unit/generateCollectionInsert.test.ts
closes #3129
Improve the concurent initialization of collections by waiting until one is finished to start another init.
- At startup add a record in the info table to state we are about to init
- When launching a new loadAdapter(), check if info table and the init record are already here. If not, proceed with init.
- If already in the process of initialization, poll the table every 100ms to see if the record remains
- When the record has disappeared, return the query
- If a previous init of a previous version does not go all the way, the version will be different. Then we ignore the flag and init anyway.
=> fix: manage concurent initializations

src/runtime/internal/database.server.ts
follow up on #3129 
The `ready` flag from the database comes out as a 0-1 integer instead of a boolean.
Without this change the database always re-initializes.
=> fix: constant initialization of content tables

src/runtime/components/ContentRenderer.vue
reported in https://github.com/nuxt/content/issues/2148#issuecomment-2642846245
The content Renderer was ignoring components in the resolve function. The component object should be passed down to the MDC renderer.
=> fix(renderer): do not ignore component objects

docs/content/blog/ui-pro-docs-migration.md, docs/content/docs/1.getting-started/4.migration.md
Fixes the link to the Studio module in https://content.nuxt.com/docs/getting-started/migration#nuxt-studio-integration.
=> docs: fix nuxtlabs studio url in migration

docs/content/docs/4.utils/1.query-collection.md
#3208, #2200
Re-add the documentation section for the `count()` method, which was already added in v2 and removed somewhere on the path to the current state of the repo.
This PR adds a section to document the `count()` method so that one is able to find out such functionality is already implemented by this module.
Resolves #3208
=> docs: add missing section for the count method and fix some typos in the same file

src/utils/dev.ts
websocket can be undefined if it is disabled so we should check if it exists before accessing `close()`
=> fix: check for ws existence before closing

src/module.ts, src/presets/cloudflare-pages.ts, src/presets/node.ts, src/runtime/internal/api.ts, src/utils/templates.ts, test/basic.test.ts, test/empty.test.ts
resolves #3043
resovles #3243
resovles #3091
- resolves #3043
Due to the behavior of the `serve` package, using the `database.sql` as filename for the database dump breaks the spa apps. Renaming the filename to `sql_dump` fixes the issue
- resolves #3243
Rename `database.sql` to `sql_dump` to prevent having conflict with security services.
- resovles #3091
Instead of registering API routes under `/api/content`, module now registers APIs under `/__nuxt_content` prefix. By doing so, the module APIs will no longer conflict with user APIs and authentication.
=> fix(module): prevent conflict with auth & security tools

docs/content/docs/2.collections/3.sources.md
This PR improves the docs for the `repository` option by making it clear that it's mandatory to also specify the `include` option when using it.
=> docs: update source options

package.json, src/features/llms/module.ts, src/module.ts, src/presets/nuxthub.ts, src/runtime/app.ts, src/runtime/internal/connectors/bunsqlite.ts, src/runtime/internal/database.client.ts, src/runtime/internal/database.server.ts, src/runtime/internal/navigation.ts, src/runtime/internal/preview/collection.ts, src/runtime/internal/preview/compatibility.ts, src/runtime/internal/preview/index.ts, src/runtime/internal/query.ts, src/types/collection.ts, src/types/module.ts, src/types/query.ts, src/utils/collection.ts, src/utils/content/index.ts, src/utils/database.ts, src/utils/dev.ts, src/utils/git.ts, src/utils/preview/module.ts, src/utils/templates.ts, tsconfig.json
=> feat: refine type for `CollectionQueryBuilder.first()` method

docs/content/1.get-started/1.installation.md
Currently, running `nuxi@latest module add @nuxt/content@2` does not work due to this issue: https://github.com/nuxt/cli/issues/697.
Since the `module add` command does not allow specifying a version, I switched to the classic installation method to ensure compatibility.
=> docs(installation): fix install command

src/utils/collection.ts, test/unit/generateCollectionInsert.test.ts
When the collection schema has an object with a default value, this object gets stringified two times instead of once.
This PR removes the `JSON.stringify` for default values of objects and adds code to test for correct insert code for objects and arrays.
=> fix: generate correct collection insert for object and array default values

docs/content/studio/index.md
As mentionned in https://content.nuxt.com/docs/getting-started/migration#components <ContentSlot> are not supported in v3 so I replaced them with <slot>
=> docs: <ContentSlot> are not supported in v3, replaced by <slot>

docs/content/docs/3.files/1.markdown.md
I just spend time debugging this until I realized I need to add a schema for my collection first. I think the warning I added makes this immediately apparent.
=> docs: add clarification about schema definitions in frontmatter blocks

docs/content/docs/4.utils/1.query-collection.md
Migrating nuxt content v2 from to v3 on my blog project, I used new fetching methods andWhere and orWhere. Then I found out sample codes about them threw a type error. So I made andWhere and orWhere return CollectionQueryGroup instead of void.
I followed the sample codes in my blog project and got the error below.
```shell
src/pages/posts/[...slug].vue:40:17 - error TS2345: Argument of type '(query: CollectionQueryGroup<PostsCollectionItem>) => void' is not assignable to parameter of type 'QueryGroupFunction<PostsCollectionItem>'.
Type 'void' is not assignable to type 'CollectionQueryGroup<PostsCollectionItem>'.
40       .andWhere((query) => { query.where('draft', 'IS NULL').where('secret', 'IS NULL') })
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> docs: return CollectionQueryGroup instead of void from andWhere and orWhere

package.json, playground/components/TestA.vue, playground/components/TestB.vue, playground/components/TestC.vue, playground/components/playground.vue, pnpm-lock.yaml, src/runtime/components/ContentRenderer.vue
at the moment when the body passed to `<ContentRenderer>` changes, the new components that are required aren't loaded/processed.
=> fix: reactively load components when `body` changes

docs/content/docs/1.getting-started/4.migration.md
When I migrated nuxt content within my blog project from v2 to v3, I found type for module options changed. It would be nice if the migration guide says module options has changed and tells developers to take a look at the configuration page.
=> docs: leave note about changes in module options

src/module.ts
resolves #3298
This PR add `robots: false` to SQL dump route rules to prevent nuxt sitemap from including it.
Note: This PR won't remove your existing dump from google index, but prevent new from beeing indexed. If you need your dump to be removed from Google index, you need to perform a manual request here: https://search.google.com/search-console/removals
=> fix: update route rules to include robots directive for SQL dumps

src/runtime/presets/cloudflare-pages/database-handler.ts, src/runtime/presets/node/database-handler.ts
resolves #3291
Explicitly set the content type of SQL dump, this will help modules like html-validator to have a better understanding of API response and not treat it as HTML or something else
=> fix: explicitly set the dump's content type

src/module.ts, src/types/database.ts, src/utils/collection.ts, src/utils/database.ts, src/utils/dev.ts, test/unit/generateCollectionInsert.test.ts
When two users on diferent parts of the world open the same un-deployed nuxt content powered website, they both trigger the deployment at the same time. Since it can take a moment for data to be synchronized, both can still be running the data at the same time, including the concatenation updates.
To avoid duplicating and therefore corrupting the data, I had the idea to use a temporary hash when inserting incomplete data:
example with the hash of the record being `123456798` and the column name `content`
```
INSERT INTO _col_collection VALUES ('52', '[values-slice-1...]', '123456798-50000')
UPDATE _col_collection SET content = CONCAT(content, '[values-slice-2]'), __hash__ = '123456798-100000' WHERE id = 52 AND __hash__ =  '123456798-50000'
UPDATE _col_collection SET content = …
```
=> fix(collection): avoid double update of some record by using the hash column as index

src/module.ts, src/utils/config.ts, test/basic.test.ts, test/empty.test.ts
resolves #3307
When collections are defined in different layers, we should pass `rootDir` of that layer as collection rootDir.
=> fix(module): invalid rootDir of layer sources

docs/content/docs/2.collections/3.sources.md
This PR fixes a small typo in the `sources` section of the documentation.
In the line:
- `source: '**` includes all files within the content directory and its subdirectories.
a closing quote was missing in the glob pattern example. It has been corrected to:
- `source: '**'` includes all files within the content directory and its subdirectories.
=> docs: fix missing quote in collection sources glob pattern

src/module.ts, src/presets/aws-amplify.ts, src/presets/cloudflare-pages.ts, src/presets/node.ts, src/runtime/internal/api.ts, src/utils/templates.ts, test/basic.test.ts, test/empty.test.ts
resolves https://github.com/nuxt/content/issues/3337
Add `sql_dump` routes url file extension `.txt` (including tests). In version `3.5.0` was explicitly set dump's content type to `text/plain` (https://github.com/nuxt/content/pull/3302). It will be good practice to set the dump file extension to `.txt`.
It is known that files without extension in AWS Amplify does not work: https://github.com/aws-amplify/amplify-hosting/issues/225
When you manual deploy a Nuxt project to AWS Amplify, in local environment build the project with `nuxt generate`. The `sql_dump` file is pre-rendered without a file extension.
If `sql_dump` file is uploaded without extension to AWS Amplify, the environment will delete it, causing a 404 error, when `sql_dump` file is fetched.
Resolves #3337
=> chore: add `sql_dump` file extension

docs/content/docs/1.getting-started/2.installation.md, docs/content/docs/4.utils/1.query-collection.md, docs/content/docs/5.components/0.content-renderer.md, docs/content/docs/7.advanced/5.hooks.md
docs: fix typo
docs: add section on automatic setup via create-nuxt cli
docs: add an example usage section for hooks
docs: fix typo
N/A
Changes in this PR introduce small improvements to the Nuxt Content docs. They don't close any issues or discussions.
- I have added an example usage section to the 'Hooks' page.
- I have also added an automatic setup (using `create-nuxt`) section to the 'Installation' page.
- I fixed a couple of typos I noticed.
=> docs: fix typos, add useful information and examples

src/runtime/internal/websocket.ts
https://github.com/nuxt/content/issues/3343
Corrects the websocket client's connection URL so that it also works when a reverse proxy is used in development.
=> fix(websocket): client url for development with proxy

docs/content/docs/6.deploy/2.serverless.md
resolves #3387
D1DatabaseConfig [1] expects 'bindingName' property, documentation refers to it as 'binding'
[1]: https://github.com/nuxt/content/blob/b01e307721e3e88ae9a54997d95aaaec9a36d77f/src/types/module.ts#L9
=> docs[serverless+D1]: correct configuration property name

src/runtime/internal/api.ts
When Nuxt renders pages in SSR mode and loads content via `@nuxt/content`, it performs internal `$fetch()` calls to endpoints like:
```
/__nuxt_content/<collection>/query
```
These internal fetches previously **did not forward cookies** from the original SSR request. This broke any logic in server middleware that depends on cookie-based user authentication or authorization.
---
This project uses server middleware to control access to specific content collections based on user authentication. For example:
```ts
if (url?.includes('/__nuxt_content/')) {
const collection = getCollectionFromUrl(url)
const user = await serverSupabaseUser(event)
if (!userHasAccessToCollection(user, collection)) {
throw createError({ statusCode: 403, statusMessage: 'Unauthorized' })
}
}
```
Without the cookie …
=>  Forward SSR Cookies in Nuxt Content Internal API Requests

src/utils/dev.ts
Currently, for subfolders, path would end up being shorter than prefix, which causes it to never match. This leads to all content in those folders being ignored.
=> fix(dev): dont ignore subfolders

docs/content/docs/8.studio/3.content.md
changed ContentSlot to slot for version 3
The change in doc for this page in doc:
https://content.nuxt.com/docs/studio/content
I just copied paste the example from the Doc, but it didn't work. Eventually I figured out for version 3 nuxt/content you need to use `<slot>` instead of `<ContentSlot>`
=> docs: use vue `slot`

docs/content/docs/2.collections/1.define.md
Improves the examples, following the order of the parameters declared on `Content` type.
The Content type declaration, included on the [defineCollection() section](https://content.nuxt.com/docs/collections/define#definecollection), has the params `type` and `source`, whose order is switched on the examples used throughout the page.
=> docs: examples now have the declared argument order

docs/content/docs/7.integrations/01.i18n.md
Useless import of localeProperties
PS: Thank you for that example which comes a bit late but I know will help a lot for others!
That said, I still think this way is very difficult to use in long term when content evolves.. We systematically need to update other content.. I found a solution by using AI which creates PR of the content translated in order to review. I think we could improve the UI to help the content editor to switch between languages..
=> docs: i18n example useless import

src/runtime/internal/websocket.ts
Updated the console log prefix from "[Content]" to "[Nuxt Content: Hot Content Reload]" 
to make it clear that the messages refer to hot-reloading of Nuxt Content.
=> chore: Update WebSocket content reload logger prefix for clarity

src/runtime/internal/websocket.ts, src/utils/dev.ts
=> fix: use listhen's `publicUrl` if available
